import {test} from 'node:test';import assert from 'node:assert/strict';
import {makeProgram,PILLARS,readiness,applyDefaults,samplingStats,safeURL,directoryEntries,folderPaths,milestoneCycle,todayIn,daysBetween} from '../src/program-model.js';
import {folderZip,linkIndex} from '../src/folder-export.js';
function fixture(){const d=makeProgram({owner:'owner',start:'2026-10-10',due:'2026-10-31'});d.selected=['OPS'];d.pillars.OPS.owner='owner';d.criteria=[{id:'a',pillar:'OPS',bucket:'OPS-1',title:'Coverage',criterion:'Five per shift',owner:'owner',reviewer:'reviewer',milestoneIds:['MVP'],weight:1,gating:true,status:'Not started',kind:'number',expected:5,actual:3,comparison:'atLeast',links:[],activities:[]}];return d;}
test('13 selectable pillars provide structural buckets, not imposed criteria',()=>{const d=makeProgram();assert.equal(PILLARS.length,13);assert.equal(d.criteria.length,0);assert.equal(d.selected.length,0);assert.equal(d.sampling.every(s=>s.percent===0),true);assert(d.pillars.SEC.buckets.some(b=>b.name==='Badging & credentials'));});
test('weighted score cannot override unmet numeric gating condition',()=>{const d=fixture();d.criteria[0].status='Passed';assert.equal(readiness(d,'MVP').score,0);assert.equal(readiness(d,'MVP').eligible,false);d.criteria[0].actual=5;assert.equal(readiness(d,'MVP').score,100);assert.equal(readiness(d,'MVP').eligible,true);d.criteria.push({...d.criteria[0],id:'b',status:'Not started',weight:0.01});assert(readiness(d,'MVP').score>=99);assert.equal(readiness(d,'MVP').eligible,false);});
test('unset basis and missing selected pillar criteria are not automatically ready',()=>{const d=fixture();assert.equal(readiness(d,'HANDOFF').hasBasis,false);assert.equal(readiness(d,'HANDOFF').eligible,false);d.selected.push('SEC');d.criteria[0].actual=5;d.criteria[0].status='Passed';assert.equal(readiness(d).missingPillars,1);assert.equal(readiness(d).eligible,false);});
test('setup clock uses calendar days in the configured building time zone',()=>{assert.equal(todayIn('America/Chicago',new Date('2026-10-10T03:00:00Z')),'2026-10-09');assert.equal(daysBetween('2026-10-10','2026-10-31'),21);});
test('shared defaults preserve explicit overrides and copy field values independently',()=>{const item={owner:'exception',reviewer:'',overrides:{owner:true}},defs={owner:'default',reviewer:'r',milestoneIds:['MVP']};const updated=applyDefaults(item,defs);assert.equal(updated.owner,'exception');assert.equal(updated.reviewer,'r');assert.equal(applyDefaults(item,defs,true).owner,'default');updated.milestoneIds.push('CLOSE');assert.deepEqual(defs.milestoneIds,['MVP']);});
test('QA counts distinguish plan coverage, population coverage, passing and failure',()=>{const d=fixture(),s=d.sampling.find(s=>s.stage==='L3');s.percent=20;s.population=100;d.audits=Array.from({length:8},(_,i)=>({id:String(i),stage:'L3',status:'Passed'}));let r=samplingStats(d,s);assert.equal(r.needed,20);assert.equal(r.planPercent,40);assert.equal(r.populationPercent,8);assert.equal(r.complete,false);s.population=7;s.percent=30;assert.equal(samplingStats(d,s).needed,3);s.population=0;assert.equal(samplingStats(d,s).complete,false);});
test('QA failures block customer-gated stages even after coverage achieved',()=>{const d=fixture(),s=d.sampling.find(s=>s.stage==='L3');Object.assign(s,{percent:20,population:10,gating:true});d.audits=[{stage:'L3',status:'Passed'},{stage:'L3',status:'Passed'},{stage:'L3',status:'Failed'}];assert.equal(readiness(d,'L3').eligible,false);d.audits.pop();assert.equal(readiness(d,'L3').eligible,true);});
test('directory uses single references and excludes inactive pillars and executable URLs',()=>{const d=fixture();d.criteria[0].links=[{id:'l',title:'EOP',url:'https://example.com/EOP'},{id:'bad',url:'javascript:alert(1)'}];assert.equal(directoryEntries(d).length,1);assert.equal(safeURL('https://user:password@example.com'),'');assert.equal(safeURL('data:text/html,x'),'');d.selected=[];assert.equal(directoryEntries(d).length,0);});
test('milestone dependencies detect cycles and retain explicit predecessor boundaries',()=>{assert.equal(milestoneCycle([{id:'A',dependencyIds:['B']},{id:'B',dependencyIds:['A']}]),true);assert.equal(milestoneCycle([{id:'A',dependencyIds:['B']},{id:'B',dependencyIds:[]}]),false);const d=fixture();d.criteria[0].status='Passed';d.criteria[0].actual=5;d.milestones.find(m=>m.id==='MVP').dependencyIds=['LIVE'];assert.equal(readiness(d,'MVP').eligible,false);});
test('exported folders are sanitized and ZIP includes folder entries and an escaped external-link index',async()=>{const d=fixture(),paths=folderPaths(d,'Building / A'),index=linkIndex([{title:'<script>',url:'https://example.com',pillar:'OPS',bucket:'EOP',status:'Passed'}],'Building A');assert(paths.every(p=>!p.includes('Building / A')));assert(index.includes('&lt;script&gt;'));assert(index.includes('target="_blank"'));const bytes=new Uint8Array(await folderZip(paths,index).arrayBuffer());assert.equal(new DataView(bytes.buffer).getUint32(0,true),0x04034b50);assert(new TextDecoder().decode(bytes).includes('Threshold-Link-Index.html'));});
