export const customerRoles=[['admin','Customer administrator'],['manager','Program owner'],['verifier','Verifier'],['scoped','Scope owner / task executor'],['viewer','Viewer']];
export function licenseLabel(a){return a.suspended?'Suspended':!a.active&&['active','trialing'].includes(a.status||a.subscription_status)?'Access period ended':(a.status||a.subscription_status||'').replaceAll('_',' ')}
export function customerTotals(customers){const list=customers.filter(c=>!c.internal);return {customers:list.length,active:list.filter(c=>c.active).length,users:list.reduce((n,c)=>n+c.used_users,0),sites:list.reduce((n,c)=>n+c.used_sites,0)}}
export function createCommercial({state,ui,rpc,invoke,notice,navigate,reload}){
 const {esc,button,badge,table,heading,input,select,check,opt,options,modal,form,read,save}=ui;
 let vendor={plans:[],customers:[],activity:[],billing:{}};
 const account=()=>state().commerce.accounts.find(a=>a.workspace_id===state().workspaceId);
 const loadVendor=async()=>{vendor=await rpc('vendor_overview')};
 const metrics=items=>`<div class="grid four commercial-metrics">${items.map(([label,value,note])=>`<article class="card"><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(note)}</span></article>`).join('')}</div>`;
 function vendorView(){
  const s=customerTotals(vendor.customers),customers=vendor.customers.filter(c=>!c.internal);
  return `<div class="commercial-heading"><div><div class="eyebrow">STRUCTIVE · PLATFORM OWNER</div><h1>Your customers.<br>Your platform.</h1><p class="sub">Manage Threshold accounts, licenses and customer onboarding.</p></div><span class="vendor-mark">VENDOR CONSOLE</span></div>`+
   metrics([['Customer accounts',s.customers,'Licensed organizations'],['Active accounts',s.active,'Current access'],['Authorized users',s.users,'Across customer accounts'],['Customer sites',s.sites,'Across customer accounts']])+
   `<section class="card"><div class="row between"><div><h2>Customers</h2><p class="muted">Each customer administers its own people and site operations.</p></div>${button('Create customer','commercial-customer-new','','')}</div>`+
   table(['Customer / administrator','License','Users / sites','Onboarding',''],customers.map(c=>`<tr><td><strong>${esc(c.name)}</strong><small>${esc(c.admin_email)}</small></td><td>${badge(licenseLabel(c))}<small>${esc(c.plan)} · ${esc(c.billing_source)}</small></td><td>${c.used_users} / ${c.max_users} users<small>${c.used_sites} / ${c.max_sites} sites</small></td><td>${esc(c.onboarding||'Pending')}<small>${c.linked_users} users signed in</small></td><td>${button('Manage license','commercial-license',c.workspace_id,'link')}${button('Send setup link','commercial-send',c.workspace_id,'link')}</td></tr>`),'Your first customer will appear here after a purchase or manual provisioning.')+'</section>'+
   `<section class="card"><div class="row between"><div><h2>Plans & purchase links</h2><p class="muted">Set user and site limits. Publish an offer after connecting its Stripe price and payment link.</p></div>${button('Create plan','commercial-plan-new','','')}</div><div class="commercial-plans">`+
   vendor.plans.filter(p=>!p.internal).map(p=>`<article class="commercial-plan"><span class="eyebrow">${esc(p.code)}</span><h3>${esc(p.name)}</h3><p><b>${p.max_users}</b> users · <b>${p.max_sites}</b> sites</p>${badge(p.published?'Published':'Draft')}<div>${button('Edit plan','commercial-plan',p.id,'link')}</div></article>`).join('')+
   `${vendor.plans.some(p=>!p.internal)?'':'<p class="empty">Create your first plan to define what customers can purchase.</p>'}</div><p class="help">Plan edits set limits for new accounts. Existing manual licenses are edited individually; Stripe accounts synchronize on subscription events.</p></section>`+
   `<div class="grid two"><section class="card"><h2>Purchase onboarding</h2><ol class="commercial-steps"><li>Customer purchases a published plan through Stripe.</li><li>Verified payment creates an isolated organization and administrator.</li><li>The buyer receives a secure setup link.</li><li>The customer assigns vertical owners and invites its team.</li></ol><p class="help">${vendor.billing.processed_events?`${vendor.billing.processed_events} payment events processed. Last event: ${esc(new Date(vendor.billing.last_event).toLocaleString())}`:'No payment events received yet. Connect Stripe and sign-in email delivery before launching sales.'}</p></section><section class="card"><h2>Customer permissions</h2><p><strong>You</strong> control plans, limits and account access.</p><p><strong>Customer administrators</strong> control their people and sites.</p><p><strong>Scope owners</strong> coordinate a coded vertical. <strong>Executors</strong> work their assigned tasks.</p><p class="help">Customer operational records stay within their workspace. The vendor console provides commercial oversight.</p></section></div>`+
   `<section class="card"><h2>Recent account activity</h2>${table(['When','Customer','Action'],vendor.activity.map(x=>`<tr><td>${esc(new Date(x.created_at).toLocaleString())}</td><td>${esc(x.name||'Platform')}</td><td>${esc(x.action.replaceAll('_',' '))}</td></tr>`),'Account and license changes will appear here.')}</section>`;
 }
 function accountView(){
  const a=account();if(!a)return heading('Your account is awaiting authorization','Use the email associated with your purchase or customer invitation.');
  const canAdmin=a.role==='admin';
  return heading(a.name,'Your organization, subscription and team access.')+
   metrics([['Plan',a.plan,'Threshold license'],['Account access',licenseLabel(a),a.access_until?'Through '+new Date(a.access_until).toLocaleDateString():'No fixed end date'],['People',`${a.used_users} / ${a.max_users}`,'Active and pending users'],['Sites',`${a.used_sites} / ${a.max_sites}`,'Configured sites']])+
   (!a.active?'<div class="callout">Operational access is paused. Your saved records are retained. Contact your customer administrator or Structive to resolve the account status.</div>':'')+
   `<section class="card"><h2>${a.used_sites?'Organization administration':'Set up your organization'}</h2><ol class="commercial-steps"><li>Confirm your organization name and license.</li><li>Create your first site and its operating basis.</li><li>Authorize employees, assign scope owners, then delegate tasks.</li><li>Each employee signs in with their own authorized email.</li></ol><div class="row">${canAdmin&&a.active?button('Edit organization name','commercial-rename')+button('Manage people','commercial-people')+button('Set up a site','new-site'):''}${canAdmin&&a.billing_source==='stripe'?button('Manage subscription','commercial-portal'):''}</div><p class="help">Your customer role: ${esc(customerRoles.find(x=>x[0]===a.role)?.[1]||a.role)}. Scope ownership is assigned separately for each site and vertical.</p></section>`;
 }
 function planModal(id){
  const p=vendor.plans.find(p=>p.id===id)||{};
  modal(p.id?'Edit commercial plan':'Create commercial plan',form('commercial-plan-form',`<div class="grid two">${input('code','Plan code',p.code||'','text',`required pattern="[A-Za-z][A-Za-z0-9_-]{1,39}" ${p.id?'readonly':''}`)}${input('name','Plan name',p.name||'','text','required maxlength="100"')}${input('max_users','Included users',p.max_users||'','number','required min="1" max="100000"')}${input('max_sites','Included sites',p.max_sites||'','number','required min="1" max="10000"')}</div><h3>Purchase connection</h3><p class="help">Create the recurring price and payment link in Stripe, then link them here. Leave blank to keep a draft or use a manual contract. One subscription covers one organization.</p>${input('stripe_price_id','Stripe price ID',p.stripe_price_id||'','text','placeholder="price_…"')}${input('checkout_url','Stripe payment link',p.checkout_url||'','url','placeholder="https://buy.stripe.com/…"')}${check('published','Publish this purchase option',p.published)}<p class="help">Publishing makes the link available on the purchase page. Verify checkout, email delivery and provisioning in Stripe test mode before accepting live purchases.</p>`));
  document.querySelector('#commercial-plan-form').onsubmit=e=>{e.preventDefault();const v=read(e.target);v.published=!!v.published;save(e.target,()=>rpc('save_commercial_plan',{plan_id:p.id||null,values_json:v,expected_revision:p.revision||0}),'Commercial plan saved.');};
 }
 function customerModal(){
  const plans=vendor.plans.filter(p=>!p.internal);if(!plans.length){notice('Create a plan before provisioning a customer.');return planModal();}
  modal('Create a customer account',form('commercial-customer-form',`<p class="muted">For a customer sold through a contract or invoice. This provisions access; it does not charge a card or record a payment.</p>${input('organization','Customer organization','','text','required maxlength="150"')}<div class="grid two">${input('admin_name','Customer administrator name','','text','required maxlength="150"')}${input('admin_email','Customer administrator email','','email','required')}</div>${select('plan_id','License plan',options(plans,'',p=>`${p.name} · ${p.max_users} users · ${p.max_sites} sites`),'required')}<p class="help">The administrator controls only this customer’s organization. After creating the account, use Send setup link to deliver the invitation.</p>`,'Create isolated customer account'));
  document.querySelector('#commercial-customer-form').onsubmit=e=>{e.preventDefault();save(e.target,()=>rpc('provision_customer',read(e.target)),'Customer created. Send the administrator a setup link when email delivery is configured.');};
 }
 function licenseModal(id){
  const a=vendor.customers.find(c=>c.workspace_id===id),stripe=a.billing_source==='stripe';
  modal(a.name+' · License',form('commercial-license-form',`<p>${esc(a.plan)} · ${esc(a.billing_source)} · ${esc(a.subscription_status)}</p><p>Usage: ${a.used_users} users · ${a.used_sites} sites</p>${stripe?'<p class="help">Subscription status, plan and limits synchronize from Stripe. You can suspend platform access independently.</p>':`<div class="grid two">${input('max_users','Licensed users',a.max_users,'number',`required min="${Math.max(1,a.used_users)}"`)}${input('max_sites','Licensed sites',a.max_sites,'number',`required min="${Math.max(1,a.used_sites)}"`)}</div>${input('access_until','Access end date (optional)',a.access_until?.slice(0,10)||'','date')}`}${check('suspended','Suspend customer operational access',a.suspended)}<p class="help">Suspension retains records. Restoring an eligible license restores access.</p>`));
  document.querySelector('#commercial-license-form').onsubmit=e=>{e.preventDefault();const v=read(e.target);v.suspended=!!v.suspended;if(v.access_until)v.access_until+='T23:59:59Z';save(e.target,()=>rpc('save_customer_license',{workspace_id:id,values_json:v,expected_revision:a.revision}),'Customer license saved.');};
 }
 function renameModal(){const a=account();modal('Organization name',form('commercial-rename-form',input('organization','Organization name',a.name,'text','required maxlength="150"')));document.querySelector('#commercial-rename-form').onsubmit=e=>{e.preventDefault();save(e.target,()=>rpc('rename_customer_organization',{workspace_id:a.workspace_id,...read(e.target)}),'Organization name saved.');};}
 async function handle(name,id){
  if(name==='commercial-plan-new')return planModal();if(name==='commercial-plan')return planModal(id);
  if(name==='commercial-customer-new')return customerModal();if(name==='commercial-license')return licenseModal(id);
  if(name==='commercial-rename')return renameModal();if(name==='commercial-people')return navigate('team');
  if(name==='commercial-send'){await invoke({action:'send-setup',workspace_id:id});await reload();notice('Customer setup link sent.');return;}
  if(name==='commercial-portal'){const result=await invoke({action:'billing-portal',workspace_id:state().workspaceId});const url=new URL(result.url);if(url.protocol!=='https:'||url.hostname!=='billing.stripe.com')throw Error('Billing destination unavailable');location.assign(url.href);}
 }
 return {loadVendor,vendorView,accountView,account,handle};
}
