import {folderPaths,safeURL} from './program-model.js';
const encoder=new TextEncoder();
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function linkIndex(entries,building){return `<!doctype html><html lang="en"><meta charset="utf-8"><title>${escape(building)} — Threshold reference index</title><style>body{font:16px/1.6 system-ui;max-width:1000px;margin:40px auto;padding:20px}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #ddd;padding:10px}</style><h1>${escape(building)}</h1><p>Threshold document references. Documents remain in their external repositories.</p><table><tr><th>Folder / bucket</th><th>Reference</th><th>Status</th></tr>${entries.map(e=>`<tr><td>${escape(e.pillar+' / '+e.bucket)}</td><td><a href="${escape(safeURL(e.url))}" target="_blank" rel="noopener noreferrer">${escape(e.title)}</a></td><td>${escape(e.status)}</td></tr>`).join('')}</table></html>`;}
function crc32(bytes){let crc=0xffffffff;for(const b of bytes){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
function header(size,values){const bytes=new Uint8Array(size),v=new DataView(bytes.buffer);for(const [offset,value,width] of values)width===2?v.setUint16(offset,value,true):v.setUint32(offset,value,true);return bytes;}
export function folderZip(paths,index=''){
 const records=paths.map(path=>({name:path+'/',bytes:new Uint8Array()}));if(index)records.push({name:paths[0]+'/Threshold-Link-Index.html',bytes:encoder.encode(index)});
 const local=[],central=[];let offset=0,centralSize=0;
 for(const f of records){const name=encoder.encode(f.name),crc=crc32(f.bytes),lh=header(30,[[0,0x04034b50,4],[4,20,2],[6,0x800,2],[12,0x21,2],[14,crc,4],[18,f.bytes.length,4],[22,f.bytes.length,4],[26,name.length,2]]),ch=header(46,[[0,0x02014b50,4],[4,20,2],[6,20,2],[8,0x800,2],[14,0x21,2],[16,crc,4],[20,f.bytes.length,4],[24,f.bytes.length,4],[28,name.length,2],[38,f.name.endsWith('/')?16:0,4],[42,offset,4]]);local.push(lh,name,f.bytes);central.push(ch,name);offset+=lh.length+name.length+f.bytes.length;centralSize+=ch.length+name.length;}
 return new Blob([...local,...central,header(22,[[0,0x06054b50,4],[8,records.length,2],[10,records.length,2],[12,centralSize,4],[16,offset,4]])],{type:'application/zip'});
}
export function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function createLocalFolders(d,building,index=''){const root=await window.showDirectoryPicker({mode:'readwrite'}),paths=folderPaths(d,building);for(const path of paths){let current=root;for(const name of path.split('/'))current=await current.getDirectoryHandle(name,{create:true});}if(index){const target=await root.getDirectoryHandle(paths[0],{create:true}),file=await target.getFileHandle('Threshold-Link-Index.html',{create:true}),writer=await file.createWritable();await writer.write(index);await writer.close();}return paths.length;}
