// These definitions describe Threshold's owner-assurance workflow, not a universal commissioning standard.
export const gateDefinitions = {
 L1:{title:'Factory review',definition:'Review factory-stage testing and equipment documentation against the site’s approved requirements before equipment progresses toward installation.',steps:['Identify the applicable equipment and factory test records.','Review the required evidence and resolve mapped findings.','Verify the configured L1 requirements and record the owner decision when eligible.']},
 L2:{title:'Installation review',definition:'Confirm that installed equipment, installation records and prerequisites meet the site’s requirements for progression toward start-up.',steps:['Link installation records to the correct equipment.','Review installation checks and track outstanding work.','Verify the configured L2 requirements before requesting acceptance.']},
 L3:{title:'Start-up assurance',definition:'Review delivery-team start-up and initial operation records, including the owner’s configured document reviews and field observations.',steps:['Define and confirm the L3 test-event population.','Retain start-up evidence and record owner QA reviews.','Resolve findings and satisfy mapped requirements before acceptance.']},
 L4:{title:'Functional assurance',definition:'Review evidence that individual systems perform their specified functions and sequences under the conditions defined in the approved test program.',steps:['Confirm the L4 test-event population and observation targets.','Review functional test evidence and record owner observations.','Resolve adverse results and verify the configured L4 requirements.']},
 L5:{title:'Integrated assurance',definition:'Review evidence of coordinated system behavior, interfaces and responses under the integrated scenarios defined for the site.',steps:['Confirm the integrated scenarios included in the L5 population.','Review test results, interface findings and owner observations.','Verify mapped requirements and configured QA coverage before acceptance.']},
 G0:{title:'Activation basis',definition:'Establish the site’s operating model, accountable authorities, applicable requirements and activation plan.',steps:['Confirm the site basis and delivery organizations.','Review requirement applicability and milestone mappings.','Name the acceptance authority and verify the configured basis requirements.']},
 G1:{title:'System readiness',definition:'Confirm the site-defined prerequisites for systems to progress into the next planned operational or test condition.',steps:['Review the system readiness requirements assigned to this gate.','Resolve equipment, documentation and interface prerequisites.','Verify current evidence before requesting the owner decision.']},
 G2:{title:'Operations MVP',definition:'Establish the minimum operational capability needed for the site’s defined initial operating scope, including people, procedures, authority and response capability.',steps:['Define the initial operating scope and required capabilities.','Verify staffing, qualification, procedures and operational authority as mapped.','Review the configured G2 conditions and record an authorized decision.']},
 G3:{title:'Integrated operational readiness',definition:'Verify that the site’s operational capabilities and supporting systems work together against the configured readiness requirements.',steps:['Review integrated operational interfaces and response arrangements.','Satisfy mapped requirements and applicable commissioning QA controls.','Resolve remaining readiness constraints before acceptance.']},
 G4:{title:'Building handoff',definition:'Establish the documented transfer into operational responsibility, with the required evidence, authorities and handoff conditions verified.',steps:['Confirm the receiving organization and responsibility boundaries.','Verify required records, capabilities and applicable QA coverage.','Record the authorized handoff decision and retain its snapshot.']},
 G5:{title:'Stabilization exit',definition:'Confirm that site-defined stabilization criteria have been met after handoff and the operation is ready to leave the stabilization period.',steps:['Define site-specific stabilization requirements and evidence.','Review operating results, recurring issues and remaining constraints.','Verify the exit criteria and applicable QA before requesting acceptance.']},
 G6:{title:'Steady state',definition:'Confirm that the required operating capabilities and governance are established for sustained operations against the site’s approved steady-state criteria.',steps:['Review the sustained operating routines and capability requirements.','Confirm current evidence, responsibilities and applicable QA coverage.','Record the owner decision and continue monitoring changes to its basis.']}
};

const topic=(title,purpose,steps,result,next)=>({title,purpose,steps,result,next});
export const guideTopics = {
 'my-work':topic('Your workspace','Your sign-in determines the work available to you.', ['Scope owners see all tasks within their assigned verticals.','Executors see only tasks assigned to their own linked identity.','Open a task to review the acceptance criterion, update progress and attach evidence.','Submit finished work for the authorized verifier.'], 'Scope accountability and task execution are separate. Site acceptance remains an authorized program decision.', ['tasks','Task Register']),
 team:topic('Scopes & People','Connect each coded vertical to an accountable sponsor and individual task owners.', ['A program administrator authorizes each person’s unique email.','Assign a scope owner and team to each applicable code.','Use the Task Register to delegate work to the scope owner or team members.','The person requests a sign-in link using their authorized email. Their view follows their assignments.'], 'An authorized email must be verified before it links to the person. Suspending scoped access removes that user’s access without erasing the execution history.', ['tasks','Task Register']),
 soc:topic('SOC 2 assurance','Record the agreed SOC 2 target and connect criterion references to the work.', ['A program administrator selects Type 1 or Type 2 and the criteria categories.','Define the services and systems in scope and, for Type 2, the observation period.','Map agreed criterion references in the relevant tasks across verticals.','Assign owners, execute controls and retain supporting evidence for review.'], 'Task mappings support preparation. The examining CPA firm determines scope sufficiency and the SOC report outcome.', ['tasks','Task Register']),
 setup:topic('Overview','Use this screen to connect the site’s setup, activation milestones and current execution work.', ['Select a campus and site in the header, or choose Set up a site.','Complete the five setup steps and review the site basis.','Hover or focus a milestone for a quick definition or saved snapshot. Use its information button on a touch screen.','Select a milestone to focus the work below it. Open the register or gate decisions to act.'], 'Work completion describes task progress. Saved gate status reflects the current server evaluation; acceptance requires an authorized owner decision.', ['tasks','Task Register']),
 'setup-1':topic('Setup · Site basis','Establish which building, operating model and acceptance authority the work applies to.', ['Review the campus, site and accountable authority.','Use Edit site basis to correct the building, operating model or named authority.','Confirm the basis after reviewing requirement applicability, verification levels and milestone mappings.','Choose Save & continue to retain this step.'], 'An identifiable site and reviewed requirements provide the basis for its execution register.'),
 'setup-2':topic('Setup · Delivery team','Identify the organizations doing the work and the parties retaining authority.', ['Name the owner, commissioning lead, operator and construction lead as applicable.','Select how commissioning, operations and construction are delivered.','Open Scopes & People to authorize individual logins and assign each coded vertical a scope owner and team.','Assign the individual tasks to the scope owner or a member of that team.'], 'Existing task owners stay in place. The delivery team executes commissioning; owner assurance reviews its quality and readiness.'),
 'setup-3':topic('Setup · Sources & dates','Establish the equipment baseline, source activities and planned milestone dates.', ['Save current setup changes before opening an import or upload.','Import the master equipment list and commissioning schedule with their source revisions.','Upload scripts and supporting source records.','Enter the dates you have established, then choose Save & continue.'], 'Dates support planning. Record verification and gate acceptance separately.', ['schedule','Source Cx Schedule']),
 'setup-4':topic('Setup · QA coverage','Define the owner’s review coverage and acceptable findings for applicable L3, L4 and L5 stages.', ['In Commissioning QA, include the eligible test events in each stage population.','Set stage applicability, document-review and field-observation targets.','Confirm each population only after reviewing its completeness.','Set evidence verification levels, findings thresholds and qualifiers, then save.'], 'Samples round up to whole events. An empty or unconfirmed applicable population cannot meet its targets.', ['assurance','Commissioning QA']),
 'setup-5':topic('Setup · Review & launch','Review the delivery model, targets and assignments before completing setup.', ['Check the delivery and assurance summary.','Return to any setup step that needs correction.','Confirm that the profile has been reviewed.','Choose Finish setup to save the operating view.'], 'Finishing setup records a reviewed profile. Gate acceptance and the separate site basis review remain explicit decisions.'),
 equipment:topic('Master Equipment','Maintain the equipment records that connect source activities, tasks and evidence.', ['Download the CSV template or prepare a CSV/XLSX file.','Import the file, review column mappings and retain the producing party, source system and revision.','Review the import summary before committing it. Matching equipment codes update existing records.','Use Add equipment or Edit for individual records, then link work and evidence to the appropriate equipment.'], 'A traceable equipment baseline is available for the selected site. XLSX imports use the first sheet; imports allow up to 2,000 data rows.', ['schedule','Source Cx Schedule']),
 schedule:topic('Source Cx Schedule','Retain the delivery team’s activities and map them to the owner’s assurance view.', ['Import CSV or first-sheet XLSX activities and check the ID, date, level and milestone mappings.','Use YYYY-MM-DD dates or native Excel date cells.','Retain the producing party, source system and revision with the source file.','Use Commissioning QA to identify actual test events for the observation population.'], 'Source predecessor IDs remain source references. Configure execution-task dependencies separately in the Task Register.', ['assurance','Commissioning QA']),
 milestones:topic('Milestones','Maintain commissioning-level dates and owner acceptance gates for the selected site.', ['Review the code, track, target date and mapped requirements.','Use Configure to update the milestone name, dates and source reference.','Edit a task’s requirement to change its milestone mappings.','Use Readiness & Decisions to inspect eligibility and record acceptance.'], 'L1–L5 and G0–G6 remain separate tracks. A planned or actual date is a scheduling record.', ['readiness','Readiness & Decisions']),
 tasks:topic('Task Register','Assign and execute the coded work that supports each readiness requirement.', ['Filter by milestone, vertical, status or search text, then open a task code.','Review the acceptance criterion, evidence requirement and verification level.','Assign an owner, dates and equipment; record execution notes and blocking issues.','Attach evidence and arrange verification. Configure predecessors where needed.','An authorized verifier can complete the task once the required evidence and predecessor conditions are satisfied.'], 'A task’s status alone does not accept a gate. Administrators can configure applicability, criticality and mapped milestones.', ['evidence','Evidence & Sources']),
 capabilities:topic('Capabilities & Authority','Confirm who owns each operating capability and the authority needed to fulfill it.', ['Open the capability to review its contributing work and interfaces.','Name the accountable owner and record the integration rationale.','Identify the responsible operating party, delegated authority and authority retained by the owner.','Mark integration and authority verified after reviewing the supporting basis.'], 'Responsibility, authority and verified interfaces become explicit inputs to configured readiness requirements.', ['readiness','Readiness & Decisions']),
 evidence:topic('Evidence & Sources','Retain the records that support the work and its verification.', ['Upload a file up to 50 MB or add an HTTPS source link.','Record a meaningful title, producing party, source system and revision.','Link the task, equipment and milestone where applicable; set an expiry date when needed.','Save new revisions as separate records and submit them for verification.'], 'Uploading evidence retains the source. Verification records the reviewer’s result at a defined level.', ['reviews','Verification Queue']),
 assurance:topic('Commissioning QA','Record the owner’s document reviews and field observations of delivery-team commissioning.', ['Import source activities and include eligible L3, L4 and L5 test events in the population.','Review QA targets in setup and confirm the population after it is complete.','Retain and verify the supporting evidence before recording a positive QA review.','Record the review type, result, date, findings and rationale for each event.','Resolve findings and retain later reviews as new records.'], 'Population changes require reconfirmation. Later adverse reviews or expired/rejected evidence can remove positive coverage.', ['setup','Overview']),
 reviews:topic('Verification Queue','Evaluate evidence against the linked requirement and record the result.', ['Open the source and review its revision, task criterion and required evidence.','Select the verification level actually performed.','Record Verified or Rejected with the observed result and rationale.','Review the retained history when evaluating later revisions or changed conditions.'], 'The current valid review must meet the requirement’s verification level. Rejected or expired evidence can affect previously accepted readiness.', ['readiness','Readiness & Decisions']),
 readiness:topic('Readiness & Decisions','Review the saved basis for eligibility and make an authorized owner decision.', ['Re-evaluate to refresh requirements, evidence, dependencies, capability controls and QA.','Read the outstanding reasons on each gate and open its tasks to resolve them.','When eligible, an authorized administrator or manager can record acceptance with a named authority and rationale.','Review accepted or degraded states; use withdrawal when an authorized decision requires it.'], 'Eligible for Acceptance and Accepted are different states. Decisions retain an immutable snapshot. Changed conditions can degrade an earlier acceptance.', ['history','Change History']),
 history:topic('Change History','Trace execution changes and the basis retained with owner decisions.', ['Review acceptance decisions by time, milestone and named authority.','Open a decision snapshot to inspect its retained basis or download it.','Review the latest 150 audited changes and compare before/after values.','Use the relevant work screen to correct a record through the normal workflow.'], 'History preserves what was recorded. A decision snapshot is historical; consult Readiness & Decisions for the current state.', ['readiness','Readiness & Decisions'])
};

export function resolveGuide(key) {
 if(key?.startsWith('gate:')) {const code=key.slice(5),gate=gateDefinitions[code];if(gate)return topic(`${code} · ${gate.title}`,gate.definition,gate.steps,'The site’s approved requirements, applicability and verification levels govern this milestone. Review its saved evaluation before an owner decision.',['readiness','Readiness & Decisions']);}
 return guideTopics[key]||guideTopics.setup;
}
