export const PILLARS = [
 ['GOV','Governance',['Readiness ownership','Roles & authorities','Acceptance decisions','Escalation','Operating boundaries','Handoff responsibilities']],
 ['OPS','Operations',['Staffing & shift coverage','Operating procedures','Emergency operating procedures','Shift turnover & rounds','Alarm response','Escalation','Operating access']],
 ['MNT','Maintenance & Facility Management',['Asset reconciliation','Maintenance basis','CMMS readiness','Initial maintenance','Work control','Tools & service coverage','General building services']],
 ['REL','Reliability',['Criticality','Failure & recovery','Baseline condition','Performance limits','Defect trends','Monitoring ownership']],
 ['TRN','Training & Qualification',['Role requirements','Equipment familiarization','Task qualification','Emergency response qualification','Qualified shift coverage','Authorization records']],
 ['EHS','EHS & Safe Work',['Applicable requirements','Safe work programs','Permits & isolation','Emergency arrangements','Waste streams','Environmental obligations']],
 ['SEC','Physical Security',['Manning model','Badging & credentials','Controlled access','Cameras & monitoring','Visitors & vendors','MMR & server-room access','Supporting networks & servers']],
 ['LOG','Logistics & Spares',['Critical spares','Receiving & storage','Inventory','Consumables','Tools','Procurement & replenishment']],
 ['CTL','BMS / EPMS & Controls',['Point & asset mapping','Graphics','Alarms & priorities','Sequences & settings','Trends','Operator access','Backups','Response validation']],
 ['BCM','Emergency Response & Continuity',['Response scenarios','Command roles','Communications','External responders','Recovery priorities','Drills','Continuity dependencies']],
 ['ITOT','IT / OT & Communications',['Network readiness','Accounts & permissions','Remote access','Cybersecurity requirements','Backup & recovery','Operating communications']],
 ['VEN','Vendor & Warranty Management',['Support coverage','Contacts & escalation','Response commitments','Warranty conditions','Service agreements','Outstanding obligations']],
 ['DOC','Document & Configuration Management',['Required document index','Drawings','Procedures','Test records','Revision alignment','Document access','Turnover completeness']]
].map(([code,name,buckets])=>({code,name,buckets}));
export const ASSIGNMENT_FIELDS=['owner','provider','reviewer','approver','due','milestoneIds'];
export const todayIn=(zone='UTC',now=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
export const daysBetween=(a,b)=>a&&b?Math.round((Date.parse(b+'T00:00:00Z')-Date.parse(a+'T00:00:00Z'))/86400000):null;
export const addDays=(date,n)=>new Date(Date.parse(date+'T00:00:00Z')+Number(n)*86400000).toISOString().slice(0,10);
export function safeURL(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:'';}catch{return '';}}
export function folderName(value){return String(value).replace(/[<>:"/\\|?*\x00-\x1f]/g,'-').replace(/[. ]+$/g,'').slice(0,90)||'Folder';}
export function makeProgram({owner='',start=todayIn(),due=addDays(start,21),timezone='UTC',scopeOwners={}}={}){
 const milestones=[['LIVE','Threshold Go-Live'],...['L1','L2','L3','L4','L5'].map(s=>[s,s]),['MVP','Operations MVP'],['HANDOFF','Building Handoff'],['CLOSE','Threshold Closeout']].map(([id,name])=>({id,name,date:id==='LIVE'?due:'',originalDate:id==='LIVE'?due:'',owner:id==='LIVE'?owner:'',approver:owner,dependencyIds:[],acceptedAt:'',note:''}));
 return {schema:1,setup:{owner,start,due,timezone,operationsDelivery:'Owner-operated',commissioningDelivery:'External agency',constructionDelivery:'GC / CM-led',facilityModel:'Hyperscale',operationsEstablishment:'New organization',authority:''},selected:[],pillars:Object.fromEntries(PILLARS.map(p=>[p.code,{owner:scopeOwners[p.code]||'',weight:1,setupComplete:false,buckets:p.buckets.map((name,i)=>({id:p.code+'-'+(i+1),name,defaults:{},folderName:name}))}])),criteria:[],milestones,sampling:['L1','L2','L3','L4','L5'].map(stage=>({stage,percent:0,unit:'Test events',population:0,owner:'',reviewer:'',gating:false,weight:1,scriptLink:'',sourceLink:'',explicitPopulation:false})),audits:[],inputs:[['MEL','Master equipment list','assets'],['SCHEDULE','Construction / commissioning schedule','schedule'],['SCRIPTS','Testing scripts','scripts']].map(([id,title,kind])=>({id,title,kind,owner:'',provider:'',link:'',required:false,status:'Missing',due})),folders:[],decisions:[],closedAt:''};
}
export const activeCriteria=d=>d.criteria.filter(c=>d.selected.includes(c.pillar));
export function criterionCredit(c){if(c.status!=='Passed')return 0;if(c.kind==='number'){const a=Number(c.actual),n=Number(c.expected);if(c.actual===''||!Number.isFinite(a)||!Number.isFinite(n))return 0;return (c.comparison==='atMost'?a<=n:c.comparison==='equal'?a===n:a>=n)?1:0;}return 1;}
export function samplingStats(d,s){const audits=d.audits.filter(a=>a.stage===s.stage),needed=Math.ceil(Number(s.population)*Number(s.percent)/100),observed=audits.filter(a=>['Submitted','Passed','Failed'].includes(a.status)).length,passed=audits.filter(a=>a.status==='Passed').length;return {stage:s.stage,population:Number(s.population),needed,observed,passed,failed:audits.filter(a=>a.status==='Failed').length,planPercent:needed?Math.min(100,100*observed/needed):null,populationPercent:s.population?100*observed/s.population:null,complete:Number(s.percent)===0||(needed>0&&passed>=needed&&!audits.some(a=>a.status==='Failed'))};}
export function setupGaps(d,code){const p=d.pillars[code],items=activeCriteria(d).filter(c=>c.pillar===code),gaps=[];if(!p.owner)gaps.push('Pillar owner missing');if(!items.length)gaps.push('No customer criteria defined');for(const c of items){if(!c.owner)gaps.push(c.title+': owner missing');if(!c.criterion?.trim())gaps.push(c.title+': acceptance condition missing');if(!c.milestoneIds?.length)gaps.push(c.title+': milestone missing');if(!c.reviewer)gaps.push(c.title+': reviewer missing');for(const a of c.activities||[])if(!a.owner)gaps.push(c.title+' / '+a.title+': activity owner missing');}return gaps;}
export function readiness(d,milestoneId='',trail=[]){
 const items=activeCriteria(d).filter(c=>!milestoneId||c.milestoneIds.includes(milestoneId)),pillarScores=d.selected.map(code=>{const cs=items.filter(c=>c.pillar===code),den=cs.reduce((n,c)=>n+Number(c.weight),0),num=cs.reduce((n,c)=>n+Number(c.weight)*criterionCredit(c),0);return {code,count:cs.length,score:den?100*num/den:null,weight:Number(d.pillars[code].weight),gaps:setupGaps(d,code),setupComplete:d.pillars[code].setupComplete};}),included=pillarScores.filter(p=>p.score!==null),den=included.reduce((n,p)=>n+p.weight,0);let num=included.reduce((n,p)=>n+p.score*p.weight,0);
 const relevantSampling=d.sampling.filter(s=>Number(s.percent)>0&&(!milestoneId||s.stage===milestoneId));for(const s of relevantSampling){const q=samplingStats(d,s);num+=Number(s.weight)*(q.needed?Math.min(100,100*q.passed/q.needed):0);}const totalDen=den+relevantSampling.reduce((n,s)=>n+Number(s.weight),0);
 const blockers=items.filter(c=>c.gating&&!criterionCredit(c)).map(c=>({title:c.title,owner:c.owner,id:c.id,pillar:c.pillar}));for(const s of relevantSampling)if(s.gating&&!samplingStats(d,s).complete)blockers.push({title:s.stage+' assurance incomplete',owner:s.owner,id:s.stage,pillar:'QA'});
 if(milestoneId==='LIVE')for(const code of d.selected)if(!d.pillars[code].setupComplete||setupGaps(d,code).length)blockers.push({title:code+' setup incomplete',owner:d.pillars[code].owner,pillar:code});
 const m=d.milestones.find(m=>m.id===milestoneId);if(m)for(const id of m.dependencyIds||[]){const dep=d.milestones.find(x=>x.id===id);if(!dep?.acceptedAt||trail.includes(id)||!readiness(d,id,[...trail,milestoneId]).eligible)blockers.push({title:(dep?.name||id)+' not accepted or no longer ready',owner:dep?.owner||'',id});}
 const scopedInputs=d.inputs.filter(i=>i.required&&(!milestoneId||milestoneId==='LIVE'||i.milestoneIds?.includes(milestoneId)));for(const i of scopedInputs)if(i.status!=='Received')blockers.push({title:i.title+' missing',owner:i.owner,id:i.id});
 const missingPillars=!milestoneId?pillarScores.filter(p=>!p.count).length:0,hasBasis=items.length+relevantSampling.length>0||(milestoneId==='LIVE'&&d.selected.length>0);return {score:totalDen?Math.round(num/totalDen*10)/10:null,pillars:pillarScores,blockers,count:items.length,passed:items.filter(criterionCredit).length,eligible:hasBasis&&!blockers.length&&missingPillars===0,hasBasis,missingPillars};
}
export function applyDefaults(item,defaults,force=false){const next=structuredClone(item);next.inherited||={};for(const k of ASSIGNMENT_FIELDS)if(k in defaults&&(force||!next.overrides?.[k])){next[k]=structuredClone(defaults[k]);next.inherited[k]=true;if(force&&next.overrides)delete next.overrides[k];}return next;}
export function directoryEntries(d){return activeCriteria(d).flatMap(c=>(c.links||[]).filter(l=>safeURL(l.url)).map(l=>({id:l.id,title:l.title||c.title,url:safeURL(l.url),pillar:c.pillar,bucket:c.bucket,folderId:l.folderId||'',criterionId:c.id,status:c.status,owner:c.owner}))).concat(activeCriteria(d).flatMap(c=>(c.activities||[]).flatMap(a=>(a.links||[]).filter(l=>safeURL(l.url)).map(l=>({id:l.id,title:l.title||a.title,url:safeURL(l.url),pillar:c.pillar,bucket:c.bucket,folderId:l.folderId||'',criterionId:c.id,status:a.status,owner:a.owner})))),d.inputs.filter(i=>safeURL(i.link)).map(i=>({id:i.id,title:i.title,url:safeURL(i.link),pillar:'BASIS',bucket:i.kind,criterionId:'',status:i.status,owner:i.owner})),d.audits.flatMap(a=>(a.links||[]).filter(l=>safeURL(l.url)).map(l=>({id:l.id,title:l.title||a.title,url:safeURL(l.url),pillar:'QA',bucket:a.stage,folderId:l.folderId||'',criterionId:a.id,status:a.status,owner:a.owner}))),d.audits.filter(a=>safeURL(a.scriptLink)).map(a=>({id:a.id,title:a.title+' — script',url:safeURL(a.scriptLink),pillar:'QA',bucket:a.stage,criterionId:a.id,status:a.status,owner:a.owner})));}
export function folderPaths(d,building){const root=folderName(building),paths=[root,root+'/00 - Building Basis',root+'/90 - Commissioning Assurance'];for(const s of d.sampling)if(Number(s.percent)>0)paths.push(root+'/90 - Commissioning Assurance/'+s.stage);for(const code of d.selected){const p=PILLARS.find(x=>x.code===code),base=root+'/'+folderName(code+' - '+p.name);paths.push(base);for(const b of d.pillars[code].buckets)paths.push(base+'/'+folderName(b.folderName||b.name));}
 const extra=new Map();function extraPath(f,visiting=new Set()){if(visiting.has(f.id))throw Error('Folder hierarchy contains a cycle.');if(extra.has(f.id))return extra.get(f.id);visiting.add(f.id);const parent=d.folders.find(x=>x.id===f.parentId);let base;if(parent)base=extraPath(parent,visiting);else if(f.pillar&&d.selected.includes(f.pillar)){const p=PILLARS.find(x=>x.code===f.pillar),b=d.pillars[f.pillar].buckets.find(x=>x.id===f.bucket);base=root+'/'+folderName(f.pillar+' - '+p.name)+(b?'/'+folderName(b.folderName||b.name):'');}else base=root;const path=base+'/'+folderName(f.name);extra.set(f.id,path);return path;}for(const f of d.folders)if(!f.pillar||d.selected.includes(f.pillar))paths.push(extraPath(f));return [...new Set(paths)];}
export function milestoneCycle(milestones){const visiting=new Set(),done=new Set();function visit(id){if(visiting.has(id))return true;if(done.has(id))return false;visiting.add(id);for(const next of milestones.find(m=>m.id===id)?.dependencyIds||[])if(visit(next))return true;visiting.delete(id);done.add(id);return false;}return milestones.some(m=>visit(m.id));}

export function customFolderPath(d,building,id,trail=[]){const root=folderName(building),f=d.folders.find(f=>f.id===id);if(!f)return root;if(trail.includes(id))throw Error('Folder hierarchy contains a cycle.');const p=PILLARS.find(p=>p.code===f.pillar),b=d.pillars[f.pillar]?.buckets.find(b=>b.id===f.bucket);const base=f.parentId?customFolderPath(d,building,f.parentId,[...trail,id]):p?root+'/'+folderName(p.code+' - '+p.name)+(b?'/'+folderName(b.folderName||b.name):''):root;return base+'/'+folderName(f.name);}
