import {PILLARS,makeProgram,addDays,todayIn,daysBetween,safeURL,activeCriteria,readiness,samplingStats,setupGaps,applyDefaults,directoryEntries,folderPaths,milestoneCycle,ASSIGNMENT_FIELDS,folderName,customFolderPath,criterionCredit} from './program-model.js';
import {folderZip,linkIndex,downloadBlob,createLocalFolders} from './folder-export.js';
import {parseFile,mapRows,fields,labels} from './records.js';
export function createProgram({state,ui,rpc,notice,navigate,paint,close,createBuild,importRecords}){
 const {esc,heading,button,table,badge,input,area,select,check,opt,options,modal,form,read}=ui;
 const $=s=>document.querySelector(s),uid=()=>crypto.randomUUID();
 let context={document:null,revision:0,editablePillars:[]},step=0,pillar='OPS',bucket='',saving=Promise.resolve(),timer,autosaveFn,selected=new Set(),loadingKey='',trial=null;
 const st=()=>trial||state(),doc=()=>context.document,manager=()=>context.manager,person=()=>context.personId;
 const roster=()=>st().people.filter(p=>p.active),name=id=>st().people.find(p=>p.id===id)?.display_name||'Unassigned';
 const personSelect=(key,label,value='',extra='')=>select(key,label,options(roster(),value,p=>p.display_name,'Unassigned'),extra);
 const canConfigure=code=>manager()||context.editablePillars.includes(code);
 const canResult=c=>manager()||context.canReview||[c.owner,c.reviewer,doc().pillars[c.pillar].owner].includes(person());
 const canOpen=c=>canResult(c)||c.activities?.some(a=>a.owner===person());
 const canVerdict=c=>manager()||context.canReview||c.reviewer===person();
 const btn=(label,action,id='',cls='secondary')=>button(label,'program-'+action,id,cls);
 const currentDate=()=>todayIn(doc()?.setup.timezone||'UTC');
 const ago=date=>{const n=daysBetween(date,currentDate());return n===null?'Date not set':n>0?n+' days overdue':n===0?'Due today':(-n)+' days remaining';};
 const link=(url,title)=>safeURL(url)?`<a href="${esc(safeURL(url))}" target="_blank" rel="noopener noreferrer">${esc(title||'Open reference')} ↗</a>`:'';
 function setStep(n){step=n;sessionStorage.setItem('threshold-step:'+st().site?.id,String(n));}
 async function load(){if(trial)return;const s=state().site;if(!s){context={document:null,revision:0,editablePillars:[]};return;}const key=s.id;const r=await rpc('get_readiness_program',{site_id:key});if(state().site?.id!==key)return;context=r;saving=Promise.resolve();loadingKey=key;step=Number(sessionStorage.getItem('threshold-step:'+key)||0);if(!doc()?.selected.includes(pillar))pillar=doc()?.selected[0]||'OPS';}
 async function persist(action,payload){
  const work=saving.catch(()=>{}).then(async()=>{if(trial){const d=doc();if(action==='initialize')context.document=payload;if(action==='settings')Object.assign(d,payload);if(action==='pillar')d.pillars[payload.code]=payload.value;if(action==='criterion'){const old=d.criteria.find(c=>c.id===payload.id);if(old&&JSON.stringify({...old,status:'',resultNote:'',actual:''})!==JSON.stringify({...payload,status:'',resultNote:'',actual:''}))payload.status='Not started';d.criteria=d.criteria.filter(c=>c.id!==payload.id).concat(payload);d.pillars[payload.pillar].setupComplete=false;}if(action==='remove_criterion')d.criteria=d.criteria.filter(c=>c.id!==payload.id);if(action==='result'&&payload.status==='Passed'){const c={...d.criteria.find(c=>c.id===payload.id),...payload};if(!c.owner||!c.reviewer||!c.criterion||!c.resultNote?.trim()||!criterionCredit(c)||(c.requiresLink&&!c.links?.length)||c.activities?.some(a=>!a.owner||a.status!=='Complete'))throw Error('Passing requires assigned ownership, supporting references and a satisfying verified result.');}if(action==='result'){Object.assign(d.criteria.find(c=>c.id===payload.id),payload);}if(action==='activity'){const c=d.criteria.find(c=>c.id===payload.criterionId);Object.assign(c.activities.find(a=>a.id===payload.id),{status:payload.status,note:payload.note,links:payload.links||[]});c.status='In progress';}if(action==='input')Object.assign(d.inputs.find(i=>i.id===payload.id),payload);if(action==='milestones')d.milestones=payload;if(action==='audits')d.audits.push(...payload);if(action==='audit'&&payload.status==='Passed'&&(!payload.owner||!payload.reviewer||!payload.scriptLink||!payload.inspectionCriteria?.trim()||!payload.observedOn||!payload.resultNote?.trim()))throw Error('Passing requires an auditor, reviewer, script, defined inspection criteria, observation date and result.');if(action==='audit')Object.assign(d.audits.find(a=>a.id===payload.id),payload);if(action==='accept'){if(!readiness(d,payload.id).eligible)throw Error('Resolve gating items and define the acceptance basis first.');const m=d.milestones.find(m=>m.id===payload.id);m.acceptedAt=new Date().toISOString();d.decisions.push({milestoneId:m.id,at:m.acceptedAt,note:payload.note,actor:'Trial user'});if(m.id==='CLOSE')d.closedAt=m.acceptedAt;}if(action==='reopen'){d.closedAt='';d.milestones.find(m=>m.id==='CLOSE').acceptedAt='';}context.revision++;sessionStorage.setItem('threshold-trial',JSON.stringify({context,trial}));}
   else context=await rpc('save_readiness_program',{site_id:state().site.id,expected_revision:context.revision,action_name:action,payload});
   const stamp=$('#program-save-state');if(stamp){stamp.textContent='Saved '+new Date().toLocaleTimeString();stamp.className='save-state';}return context;
  });saving=work;return work;
 }
 async function flush(){clearTimeout(timer);if(autosaveFn){const fn=autosaveFn;autosaveFn=null;await fn();}await saving;}
 function paintNow(){paint();}
 function saveForm(id,callback){const f=$('#'+id);f.onsubmit=async e=>{e.preventDefault();if(!f.reportValidity())return;const b=f.querySelector('button[type=submit]');b.disabled=true;try{await callback(read(f),f);close();paintNow();notice('Saved to this building.');}catch(err){$('#form-error').innerHTML=`<div class="callout error">${esc(err.message)}</div>`;b.disabled=false;}};}
 function autoForm(id,callback){const f=$('#'+id);if(!f)return;f.addEventListener('change',()=>{const status=$('#program-save-state');if(status)status.textContent='Unsaved changes';clearTimeout(timer);autosaveFn=async()=>{if(!f.reportValidity())throw Error('Complete the highlighted setup fields before continuing.');await callback(read(f),f);};timer=setTimeout(async()=>{const fn=autosaveFn;autosaveFn=null;try{await fn();}catch(err){notice(err.message,true);if(status)status.textContent='Not saved — review required';}},650);});f.onsubmit=async e=>{e.preventDefault();try{await callback(read(f),f);notice('Setup saved.');}catch(err){notice(err.message,true);}};}
 function trialBanner(){return trial?'<div class="callout trial-banner"><b>Interactive trial</b> · Changes are held in this browser session. Customer records are not affected. '+btn('Leave trial','leave-trial')+'</div>':'';}
 function empty(){return heading('Start a new build','Customer-owned commissioning QA/QC and operational readiness, one instance per building.')+`<section class="card program-intro"><div><span class="eyebrow">Define. Verify. Accept.</span><h2>Your acceptance program starts here.</h2><p>Choose the pillars, define your criteria and sampling plan, assign the people, and set your milestones. Threshold tracks readiness against the program you establish.</p><p>Structive provides portal training. Your team owns configuration and acceptance.</p></div>${state().manage?btn(state().site?'Configure this building':'Start a new build',state().site?'initialize':'new-build','',''):''}</section>`;}
 function top(title,description){return trialBanner()+heading(title,description)+(doc()?.closedAt?`<div class="callout"><b>Archived</b> · Closed ${esc(doc().closedAt)}. The evidence directory and decisions remain accessible. ${manager()?btn('Reopen with reason','reopen'):''}</div>`:'');}
 function dashboard(){if(!doc())return empty();const d=doc(),r=readiness(d),setupDone=d.selected.filter(c=>d.pillars[c].setupComplete&&!setupGaps(d,c).length).length,lateSetup=d.setup.due<currentDate()&&setupDone<d.selected.length;
  const pending=activeCriteria(d).filter(c=>c.status!=='Passed'),mine=pending.filter(c=>c.owner===person()||c.reviewer===person()||c.activities?.some(a=>a.owner===person()&&a.status!=='Complete'));
  return top('Building readiness','Commissioning assurance and operations readiness against your customer-defined acceptance program.')+`<div class="row between"><span class="muted">Threshold owner: <b>${esc(name(d.setup.owner))}</b> · ${esc(st().site.building)}</span><div class="row">${btn('Continue setup','wizard','','')}${manager()?btn('Start a new build','new-build'):''}</div></div>
  <div class="grid four program-metrics"><article class="card"><small>Weighted readiness</small><strong>${r.score===null?'—':r.score+'%'}</strong><span>${r.passed}/${r.count} criteria passed${r.missingPillars?' · '+r.missingPillars+' pillars without criteria':''}</span></article><article class="card"><small>Open gating items</small><strong>${r.blockers.length}</strong><span>Scores do not override gates</span></article><article class="card ${lateSetup?'late-card':''}"><small>Initial setup</small><strong>${setupDone}/${d.selected.length}</strong><span>${esc(ago(d.setup.due))} · Due ${esc(d.setup.due)}</span></article><article class="card"><small>My pending activities</small><strong>${mine.length}</strong><span>Inputs, criteria and reviews assigned to you</span></article></div>
  <section class="card program-timeline"><div class="row between"><h2>Milestone timeline</h2>${btn('Manage milestones','milestones')}</div><div class="milestone-strip">${d.milestones.map(m=>{const a=readiness(d,m.id),status=m.acceptedAt?(a.eligible?'Accepted':'Degraded'):!a.hasBasis?'Not configured':a.blockers.length?'Blocked':'Eligible';return `<button type="button" class="milestone-tile ${status==='Blocked'||status==='Degraded'?'tile-blocked':''}" data-action="program-milestone" data-id="${esc(m.id)}"><small>${esc(m.id)}</small><b>${esc(m.name)}</b><span>${esc(m.date||'Date not set')}</span><span>${esc(status)}</span><small>${m.acceptedAt?'Accepted '+esc(m.acceptedAt.slice(0,10)):esc(ago(m.date))}</small></button>`;}).join('')}</div></section>
  <section class="card"><div class="row between"><h2>Pillar readiness & accountability</h2>${btn('Configure pillars','step','1')}</div>${table(['Pillar / owner','Setup','Readiness','Gating',''],r.pillars.map(p=>{const meta=PILLARS.find(x=>x.code===p.code),late=d.setup.due<currentDate()&&(!p.setupComplete||p.gaps.length);return `<tr><td><b>${esc(p.code+' · '+meta.name)}</b><small>${esc(name(d.pillars[p.code].owner))}</small></td><td>${badge(p.setupComplete&&!p.gaps.length?'Complete':late?'Overdue':'In progress')}<small>${p.gaps.length} setup gaps</small></td><td>${p.score===null?'Not configured':p.score.toFixed(1)+'%'}<small>${p.count} criteria · weight ${p.weight}</small></td><td>${r.blockers.filter(b=>b.pillar===p.code).length}</td><td>${btn('Open','pillar',p.code,'link')}</td></tr>`;}))}</section>
  <div class="grid two"><section class="card"><h2>What blocks acceptance</h2>${table(['Requirement','Accountable',''],r.blockers.map(b=>`<tr><td>${esc(b.title)}</td><td>${esc(name(b.owner))}</td><td>${d.criteria.some(c=>c.id===b.id)?btn('Open','result',b.id,'link'):btn('Setup','wizard','','link')}</td></tr>`),'No configured gating item is currently open.')}</section><section class="card"><h2>Input requests</h2>${inputTable(d.inputs)}</section></div>
  <section class="card"><div class="row between"><h2>Commissioning assurance</h2>${btn('Inspect / review','qa')}</div>${samplingTable()}</section>
  <section class="card"><h2>My work & pending reviews</h2>${criterionTable(mine)}${table(['Inspection','Date','Assignment','Status',''],d.audits.filter(a=>a.owner===person()||a.reviewer===person()).map(a=>`<tr><td>${esc(a.stage+' · '+a.title)}</td><td>${esc(a.date||'Not set')}</td><td>${esc(name(a.owner))}<small>Reviewer: ${esc(name(a.reviewer))}</small></td><td>${badge(a.status)}</td><td>${btn('Open','audit',a.id,'link')}</td></tr>`),'No inspections assigned to you.')}</section>`;
 }
 function inputTable(inputs){return table(['Input / provider','Coordinator','Due / status',''],inputs.map(i=>`<tr><td>${esc(i.title)}<small>${esc(i.provider||'Provider not specified')}</small>${link(i.link,'Open source')}</td><td>${esc(name(i.owner))}</td><td>${badge(i.status)}<small>${i.status==='Received'?'Received':esc(ago(i.due))}${i.required?' · Gating':''}</small></td><td>${manager()||i.owner===person()?btn('Update','input',i.id,'link'):''}</td></tr>`));}
 function criterionTable(items,configure=false){return table([configure?'Select':'Criterion','Criterion / acceptance','Owner / reviewer','Milestone / due','Weight / gate','Status',''],items.map(c=>`<tr><td>${configure?`<input type="checkbox" aria-label="Select ${esc(c.title)}" data-program-select="${esc(c.id)}" ${selected.has(c.id)?'checked':''}>`:esc(c.pillar)}</td><td><b>${esc(c.title)}</b><small class="wrap">${esc(c.criterion||'Acceptance condition not defined')}</small>${(c.links||[]).map(l=>link(l.url,l.title)).join(' · ')}</td><td>${esc(name(c.owner))}<small>Review: ${esc(name(c.reviewer))}</small></td><td>${esc(c.milestoneIds.join(', ')||'Unmapped')}<small>${c.status==='Passed'?'':esc(ago(c.due))}</small></td><td>${esc(c.weight)}${c.critical?'<small>Critical</small>':''}${c.gating?'<small class="gating-label">Gating</small>':''}</td><td>${badge(c.status)}</td><td>${configure&&canConfigure(c.pillar)?btn('Configure','criterion',c.id,'link')+btn('Duplicate','duplicate',c.id,'link'):''}${canOpen(c)?btn('Result / links','result',c.id,'link'):''}</td></tr>`),'Add customer criteria to this bucket.');}
 const steps=['Building & clock','Pillars & owners','Criteria & assignments','Commissioning QA','Required inputs','Milestone dates','Review & launch'];
 function wizard(){if(!doc())return empty();const body=[setupStep,pillarsStep,criteriaStep,qaStep,inputsStep,milestonesView,reviewStep][step]();return top('Configure your building','Follow the wizard, pillar by pillar. Shared defaults reduce repeated entry.')+`<div class="wizard-layout"><nav class="wizard-nav" aria-label="Configuration steps">${steps.map((s,i)=>`<button type="button" data-action="program-step" data-id="${i}" ${step===i?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${esc(s)}</button>`).join('')}</nav><div class="wizard-body"><div class="row between"><h2>${esc(steps[step])}</h2><span id="program-save-state" class="save-state">Saved revision ${context.revision}</span></div>${body}<div class="wizard-footer">${step?btn('Previous','step',String(step-1)):''}<span>${step+1} / ${steps.length}</span>${step<6?btn('Save & continue','step',String(step+1),''):btn('View dashboard','home','','')}</div></div></div>`;}
 function setupStep(){const s=doc().setup;return `<form id="program-setup"><div class="grid two">${personSelect('owner','Threshold owner / single point of contact',s.owner,'required')}${input('start','Setup starts',s.start,'date','required')}${input('duration','Setup allowance (calendar days)',daysBetween(s.start,s.due),'number','min="0" max="365"')}${input('due','Threshold go-live / setup deadline',s.due,'date','required')}${select('timezone','Building time zone',['America/Chicago','America/New_York','America/Denver','America/Los_Angeles','UTC',...(!['America/Chicago','America/New_York','America/Denver','America/Los_Angeles','UTC'].includes(s.timezone)?[s.timezone]:[])].map(z=>opt(z,z,s.timezone)).join(''))}${input('authority','Acceptance authority / delegation reference',s.authority)}</div><h3>Independent delivery models</h3><div class="grid two">${select('facilityModel','Facility / service model',['Hyperscale','Enterprise','Colocation','Managed service','Edge / modular','Hybrid'].map(x=>opt(x,x,s.facilityModel)).join(''))}${select('operationsDelivery','Who operates?',['Owner-operated','Third-party operator','Hybrid by scope'].map(x=>opt(x,x,s.operationsDelivery)).join(''))}${select('commissioningDelivery','Who leads commissioning?',['In-house','External agency','Hybrid by scope'].map(x=>opt(x,x,s.commissioningDelivery)).join(''))}${select('constructionDelivery','Construction delivery',['GC / CM-led','Design-build / EPC','Owner-managed contractors','Phased / hybrid','No active construction'].map(x=>opt(x,x,s.constructionDelivery)).join(''))}${select('operationsEstablishment','Operations establishment',['New organization','Mobilize existing operator','Operator transfer','Enhance existing organization'].map(x=>opt(x,x,s.operationsEstablishment)).join(''))}</div><p class="help">Fields save after a change. The dashboard starts measuring setup against this deadline immediately.</p><button type="submit">Save setup</button></form>`;}
 function pillarsStep(){return `<p>Select the pillars for this building. Recommended buckets provide a starting structure; your team writes the criteria.</p><div class="program-pillar-grid">${PILLARS.map(p=>{const enabled=doc().selected.includes(p.code),s=doc().pillars[p.code];return `<article class="card pillar-choice ${enabled?'selected':''}"><div class="row between"><label class="check"><input type="checkbox" data-program-pillar="${p.code}" ${enabled?'checked':''} ${!manager()?'disabled':''}><b>${esc(p.code)}</b></label>${badge(enabled?'Selected':'Not selected')}</div><h3>${esc(p.name)}</h3><p>${p.buckets.length} recommended buckets</p><p>Owner: <b>${esc(name(s.owner))}</b></p>${canConfigure(p.code)?btn('Owner & weight','pillar-settings',p.code):''}</article>`;}).join('')}</div><p class="help">Unselected pillars are excluded from readiness scoring. Their previous configuration is retained if you select them again.</p>`;}
 function criteriaStep(){const codes=doc().selected;if(!codes.length)return '<p>Select at least one pillar first.</p>';if(!codes.includes(pillar))pillar=codes[0];const p=doc().pillars[pillar];if(!p.buckets.some(b=>b.id===bucket))bucket=p.buckets[0]?.id||'';const b=p.buckets.find(x=>x.id===bucket),items=activeCriteria(doc()).filter(c=>c.pillar===pillar&&c.bucket===bucket);return `<div class="grid two">${select('pillar-current','Pillar',codes.map(c=>opt(c,c+' · '+PILLARS.find(p=>p.code===c).name,pillar)).join(''),'id="program-pillar-select"')}${select('bucket-current','Parent bucket',p.buckets.map(b=>opt(b.id,b.name,bucket)).join(''),'id="program-bucket-select"')}</div><p class="muted">Pillar owner: ${esc(name(p.owner))} · ${p.setupComplete?'Setup complete':'Setup in progress'}</p><div class="toolbar">${canConfigure(pillar)?btn('Add criterion','new-criterion',bucket,'')+btn('Bucket defaults','defaults',bucket)+btn('Edit buckets','buckets',pillar)+btn('Bulk assignments','bulk',bucket)+btn('Mark pillar setup complete','complete-pillar',pillar):''}</div>${b?`<div class="callout">${esc(b.name)} defaults: owner ${esc(name(b.defaults.owner))} · provider ${esc(b.defaults.provider||'not set')} · reviewer ${esc(name(b.defaults.reviewer))}. Individual overrides are preserved.</div>`:''}${criterionTable(items,true)}`;}
 function samplingTable(){return table(['Stage / target','Population / required','Observed / passed','Plan progress','Gate'],doc().sampling.map(s=>{const q=samplingStats(doc(),s);return `<tr><td><b>${s.stage}</b><small>${s.percent}% · ${esc(s.unit)}</small></td><td>${q.population} / ${q.needed}</td><td>${q.observed} / ${q.passed}<small>${q.failed} failed</small></td><td>${q.planPercent===null?'Not audited':q.planPercent.toFixed(1)+'%'}<small>${q.populationPercent===null?'Population not defined':q.populationPercent.toFixed(1)+'% of population'}</small></td><td>${s.gating?badge(q.complete?'Satisfied':'Blocked'):'Not gating'}</td></tr>`;}));}
 function qaStep(){return `<p>Define the QA/QC scope your team will perform. Percentages are customer choices; recommendations do not impose minimums.</p>${samplingTable()}<div class="toolbar">${manager()?btn('Configure sampling & owners','sampling')+btn('Create inspection assignments','generate-audits'):''}${btn('Open inspections','qa')}</div><p class="help">Sampling counts round up to whole events. Audit completion and passing results are reported separately. A selected stage with no defined population cannot claim completed coverage.</p>`;}
 function inputsStep(){return `<p>Assign coordinators to obtain the building basis from construction, design, commissioning, or the operator. Documents remain in your repository.</p>${inputTable(doc().inputs)}<div class="toolbar">${manager()?btn('Configure input requests','inputs-config')+btn('Import MEL','import','assets')+btn('Import construction / Cx schedule','import','schedule'):''}</div><p class="help">Structured imports retain equipment and activity data. Reference links point to your original documents.</p>`;}
 function milestonesView(){if(!doc())return empty();return `<p>Set target dates, owners, acceptance authorities, and optional dependencies. Original dates remain visible after rescheduling.</p>${manager()?btn('Add milestone','new-milestone','',''):''}${table(['Milestone','Target / original','Accountable owner','Readiness / gates',''],doc().milestones.map(m=>{const r=readiness(doc(),m.id);return `<tr><td><b>${esc(m.name)}</b><small>${esc(m.id)}</small></td><td>${esc(m.date||'Not set')}<small>${m.originalDate&&m.originalDate!==m.date?'Original: '+esc(m.originalDate):esc(ago(m.date))}</small></td><td>${esc(name(m.owner))}</td><td>${r.score===null?'—':r.score+'%'}<small>${r.blockers.length} gates open · ${m.acceptedAt?(r.eligible?'Accepted':'Degraded'):r.hasBasis?'Awaiting acceptance':'Not configured'}</small></td><td>${manager()?btn('Configure','edit-milestone',m.id,'link'):''}${btn('View','milestone',m.id,'link')}</td></tr>`;}))}`;}
 function reviewStep(){const d=doc(),r=readiness(d,'LIVE');return `<h3>Configuration readiness</h3>${table(['Pillar','Owner','Setup gaps','Status'],d.selected.map(code=>{const gaps=setupGaps(d,code);return `<tr><td>${esc(code)}</td><td>${esc(name(d.pillars[code].owner))}</td><td>${gaps.map(esc).join('<br>')||'Assignments and criteria defined'}</td><td>${badge(d.pillars[code].setupComplete&&!gaps.length?'Complete':'Incomplete')}</td></tr>`;}))}<div class="callout">${r.eligible?'The configured go-live basis is eligible for customer acceptance.':r.blockers.map(b=>esc(b.title)).join('<br>')||'Select pillars and define the setup basis.'}</div>${btn('Review go-live decision','milestone','LIVE','')}`;}
 function qaView(){if(!doc())return empty();return top('Commissioning QA/QC','Customer-selected inspection coverage, named auditors, script references, findings and review results.')+qaStep()+table(['Stage / inspection','Equipment / script','Due / observed','Auditor / reviewer','Status / findings',''],doc().audits.map(a=>`<tr><td>${esc(a.stage)}<small>${esc(a.title)}</small></td><td>${esc(a.assetCode||'Not linked')}<small>${link(a.scriptLink,'Script')}</small></td><td>${esc(a.date||'Not set')}<small>${a.observedOn?'Observed '+esc(a.observedOn):esc(ago(a.date))}</small></td><td>${esc(name(a.owner))}<small>${esc(name(a.reviewer))}</small></td><td>${badge(a.status)}<small>${esc(a.findings||'')}</small></td><td>${btn('Open','audit',a.id,'link')}</td></tr>`),'Generate inspections from your schedule or add a defined inspection.');}
 function directoryView(){if(!doc())return empty();const d=doc(),entries=directoryEntries(d),paths=folderPaths(d,st().site.building),root=paths[0];const map=new Map();for(const path of paths){const parent=path.includes('/')?path.slice(0,path.lastIndexOf('/')):'';if(!map.has(parent))map.set(parent,[]);map.get(parent).push(path);}const entryPath=e=>{if(e.folderId){const f=d.folders.find(f=>f.id===e.folderId);if(f){return customFolderPath(d,st().site.building,f.id);}}if(e.pillar==='BASIS')return root+'/00 - Building Basis';if(e.pillar==='QA')return root+'/90 - Commissioning Assurance/'+e.bucket;const p=PILLARS.find(p=>p.code===e.pillar),b=d.pillars[e.pillar].buckets.find(b=>b.id===e.bucket);return paths.find(pth=>pth===root+'/'+folderName(e.pillar+' - '+p.name)+'/'+folderName(b?.folderName||b?.name))||root;};
 const draw=path=>`<details class="directory-folder" open><summary>${esc(path.split('/').at(-1))}</summary><div>${entries.filter(e=>entryPath(e)===path).map(e=>`<div class="directory-reference">${link(e.url,e.title)}<small>${esc(e.status)} · ${esc(name(e.owner))} ${e.criterionId?btn(d.audits.some(a=>a.id===e.criterionId)?'Inspection':'Criterion','result',e.criterionId,'link'):''}</small></div>`).join('')}${(map.get(path)||[]).map(draw).join('')}</div></details>`;
 const missing=activeCriteria(d).filter(c=>c.requiresLink&&!c.links?.length);
 return top('Document Directory','A hierarchical reference map and folder template. Source documents remain in your repositories.')+`<div class="toolbar">${manager()?btn('Add subfolder','new-folder')+doc().folders.map(f=>btn('Edit '+f.name,'edit-folder',f.id)).join(''):''}${btn('Export folder structure','export-folders','','')}${typeof window.showDirectoryPicker==='function'?btn('Create folders on this computer','local-folders'):''}${btn('Export link index','export-index')}<label class="check"><input type="checkbox" id="program-export-index" checked>Include clickable link index in ZIP</label></div><p class="help">${entries.length} linked references · ${paths.length} folders. Directory placement is a suggested organization; it does not move external files.</p><section class="card document-tree">${draw(root)}</section>${missing.length?`<section class="card"><h2>Required references not yet supplied</h2>${table(['Criterion','Owner',''],missing.map(c=>`<tr><td>${esc(c.title)}</td><td>${esc(name(c.owner))}</td><td>${canResult(c)?btn('Add link','result',c.id,'link'):''}</td></tr>`))}</section>`:''}`;
 }
 function historyView(){if(!doc())return empty();return top('Readiness decisions','Acceptance records and target-date history for this building.')+table(['When','Milestone','Actor / note'],doc()?.decisions.map(x=>`<tr><td>${esc(x.at)}</td><td>${esc(x.milestoneId)}</td><td>${esc(x.actor)}<small class="wrap">${esc(x.note)}</small></td></tr>`)||[],'No acceptance decisions recorded.');}
 function mount(route){if(!doc()||doc().closedAt)return;const wrap=$('#content');
  if(route==='program-wizard'&&step===0){const f=$('#program-setup');f?.querySelector('[name=duration]').addEventListener('change',()=>{f.querySelector('[name=due]').value=addDays(f.querySelector('[name=start]').value,f.querySelector('[name=duration]').value);});if(!manager()){f?.querySelectorAll('input,select,textarea,button[type=submit]').forEach(x=>x.disabled=true);return;}autoForm('program-setup',async v=>{const setup={...doc().setup,...v};delete setup.duration;await persist('settings',{setup});const milestones=structuredClone(doc().milestones);milestones.find(m=>m.id==='LIVE').date=setup.due;await persist('milestones',milestones);});}
  $('#program-pillar-select')?.addEventListener('change',async e=>{await flush();pillar=e.target.value;bucket='';paintNow();});$('#program-bucket-select')?.addEventListener('change',async e=>{await flush();bucket=e.target.value;paintNow();});
  wrap?.querySelectorAll('[data-program-select]').forEach(x=>x.addEventListener('change',()=>{x.checked?selected.add(x.dataset.programSelect):selected.delete(x.dataset.programSelect);}));
  wrap?.querySelectorAll('[data-program-pillar]').forEach(x=>x.addEventListener('change',async()=>{try{const selected=doc().selected.filter(c=>c!==x.dataset.programPillar);if(x.checked)selected.push(x.dataset.programPillar);await persist('settings',{selected});paintNow();}catch(e){x.checked=!x.checked;notice(e.message,true);}}));
 }
 function assignments(c){return `<div class="grid two">${personSelect('owner','Accountable criterion owner',c.owner)}${input('provider','Deliverable provider / organization',c.provider)}${personSelect('reviewer','Reviewer / verifier',c.reviewer)}${personSelect('approver','Approver, if required',c.approver)}${input('due','Due date',c.due,'date')}</div><fieldset><legend>Applicable milestones</legend><div class="grid three">${doc().milestones.map(m=>check('mile_'+m.id,m.name,c.milestoneIds?.includes(m.id))).join('')}</div></fieldset>`;}
 const getAssignments=(v)=>({owner:v.owner,provider:v.provider,reviewer:v.reviewer,approver:v.approver,due:v.due,milestoneIds:doc().milestones.filter(m=>v['mile_'+m.id]).map(m=>m.id)});
 function linksEditor(links=[]){return `<div id="program-links">${links.map(l=>linkRow(l)).join('')}</div>${btn('Add reference link','add-link')}<p class="help">Links open externally in a new tab and appear automatically in Document Directory.</p>`;}
 function linkRow(l={}){return `<div class="program-link-row" data-link-id="${esc(l.id||uid())}">${input('link-title','Display name',l.title||'')}${input('link-url','External hyperlink',l.url||'','url')}${select('link-folder','Directory folder (optional)',opt('','Criterion bucket',l.folderId||'')+doc().folders.map(f=>opt(f.id,f.name,l.folderId)).join(''))}${btn('Remove','remove-link','','link')}</div>`;}
 function collectLinks(f){return [...f.querySelectorAll('.program-link-row')].map(row=>({id:row.dataset.linkId,title:row.querySelector('[name=link-title]').value,url:row.querySelector('[name=link-url]').value,folderId:row.querySelector('[name=link-folder]').value})).filter(l=>l.url).map(l=>{const url=safeURL(l.url);if(!url)throw Error('Use a valid HTTP or HTTPS hyperlink.');return {...l,url};});}
 function activityRows(activities=[]){return `<div id="program-activities">${activities.map(activityRow).join('')}</div>${btn('Add input / inspection / verification activity','add-activity')}`;}
 function activityRow(a={}){return `<div class="program-activity-row" data-activity-id="${esc(a.id||uid())}">${input('activity-title','Activity / contribution',a.title||'')}${personSelect('activity-owner','Accountable person',a.owner||'')}${input('activity-provider','External provider, if applicable',a.provider||'')}${input('activity-due','Due date',a.due||'','date')}${btn('Remove','remove-activity','','link')}</div>`;}
 function collectActivities(f,prior=[]){return [...f.querySelectorAll('.program-activity-row')].map(row=>{const id=row.dataset.activityId,old=prior.find(a=>a.id===id);return {id,title:row.querySelector('[name=activity-title]').value,owner:row.querySelector('[name=activity-owner]').value,provider:row.querySelector('[name=activity-provider]').value,due:row.querySelector('[name=activity-due]').value,status:old?.status||'Not started',note:old?.note||'',links:old?.links||[]};}).filter(a=>a.title);}
 function criterionModal(id='',duplicate=false){const existing=doc().criteria.find(c=>c.id===id);if(existing){pillar=existing.pillar;bucket=existing.bucket;}if(!canConfigure(pillar))throw Error('Pillar owner required.');const b=doc().pillars[pillar].buckets.find(b=>b.id===bucket),base={id:uid(),pillar,bucket,title:'',criterion:'',kind:'check',expected:'',actual:'',comparison:'atLeast',weight:1,gating:undefined,critical:false,requiresLink:false,status:'Not started',resultNote:'',links:[],activities:[],milestoneIds:[],owner:'',provider:'',reviewer:'',approver:'',due:'',overrides:{},inherited:{}};
  const c=duplicate?{...structuredClone(existing),id:uid(),title:existing.title+' (copy)',status:'Not started',actual:'',resultNote:'',links:[],activities:existing.activities.map(a=>({...a,id:uid(),status:'Not started',note:''}))}:existing?structuredClone(existing):applyDefaults(base,b.defaults);
  modal(existing&&!duplicate?'Configure criterion':'Add customer criterion',form('program-criterion',`<p class="muted">${esc(pillar)} / ${esc(b.name)} · ${existing&&!duplicate?'Edit configuration; material changes reopen verification.':'Assignments start from bucket defaults.'}</p>${input('title','Line item / criterion name',c.title,'text','required')}${area('criterion','Customer-defined passing condition',c.criterion,'required')}<div class="grid three">${select('kind','Input / evaluation type',['check','number','document'].map(x=>opt(x,{check:'Review / inspection',number:'Numeric threshold',document:'Document reference'}[x],c.kind)).join(''))}${input('expected','Required numeric value (if numeric)',c.expected,'number','step="any"')}${select('comparison','Numeric passing rule',['atLeast','atMost','equal'].map(x=>opt(x,{atLeast:'At least',atMost:'At most',equal:'Exactly'}[x],c.comparison)).join(''))}${input('weight','Readiness weight',c.weight,'number','min="0.01" step="any" required')}</div>${check('critical','Customer considers this critical',c.critical)}${select('gating','Does failure gate acceptance?',opt('','Choose gating or not gating',c.gating===undefined?'':String(c.gating))+opt('true','Yes — gating',String(c.gating))+opt('false','No — not gating',String(c.gating)),'required')}${check('requiresLink','A supporting reference link is required',c.requiresLink)}<h3>Assignments</h3>${assignments(c)}<div class="row">${btn('Same assignments as previous item','same-previous',c.id)}${btn('Use bucket defaults','use-defaults',bucket)}</div><p class="help">${ASSIGNMENT_FIELDS.filter(k=>c.inherited?.[k]&&!c.overrides?.[k]).map(k=>esc(k)+' from bucket default').join(' · ')||'Individual assignments'}</p><h3>Separately assigned contributions</h3>${activityRows(c.activities)}<h3>External references</h3>${linksEditor(c.links)}${existing&&!duplicate?btn('Remove criterion','remove-criterion',c.id,'danger'):''}`,'Save criterion'));
  $('#program-criterion').dataset.original=JSON.stringify(c);saveForm('program-criterion',async(v,f)=>{const next={...c,...getAssignments(v),title:v.title,criterion:v.criterion,kind:v.kind,expected:v.expected,comparison:v.comparison,weight:Number(v.weight),critical:!!v.critical,gating:v.gating==='true',requiresLink:!!v.requiresLink,links:collectLinks(f),activities:collectActivities(f,c.activities)};next.overrides={...c.overrides};for(const key of ASSIGNMENT_FIELDS)if(JSON.stringify(next[key])!==JSON.stringify(b.defaults[key]??''))next.overrides[key]=true;else delete next.overrides[key];if(next.kind==='number'&&v.expected==='')throw Error('Define the required numeric value.');await persist('criterion',next);});
  $('#program-criterion [name=critical]').addEventListener('change',e=>{if(e.target.checked){$('#program-criterion [name=gating]').focus();notice('Choose explicitly whether this critical item is gating.');}});
 }
 function resultModal(id){const c=doc().criteria.find(c=>c.id===id);if(!c){if(doc().audits.some(a=>a.id===id))return auditModal(id);throw Error('Criterion not found.');}const allowed=canResult(c)&&!doc().closedAt;const states=canVerdict(c)?['Not started','In progress','Submitted','Passed','Failed']:['Not started','In progress','Submitted'];modal(c.title,form('program-result',`<div class="callout"><b>Passing condition</b><p>${esc(c.criterion)}</p>${c.kind==='number'?`Required: ${esc(c.comparison)} ${esc(c.expected)}`:''}<p>Owner: ${esc(name(c.owner))} · Reviewer: ${esc(name(c.reviewer))} · ${c.gating?'Gating':'Not gating'}</p></div><div class="grid two">${select('status','Result / verification status',states.map(x=>opt(x,x,c.status)).join(''))}${c.kind==='number'?input('actual','Actual measured value',c.actual,'number','step="any"'):''}</div>${area('resultNote','Observed result / review rationale',c.resultNote)}<h3>Reference links</h3>${linksEditor(c.links)}<h3>Assigned activities</h3>${table(['Activity / provider','Owner / due','Status',''],(c.activities||[]).map(a=>`<tr><td>${esc(a.title)}<small>${esc(a.provider||'')}</small></td><td>${esc(name(a.owner))}<small>${esc(a.due||'Not set')}</small></td><td>${badge(a.status)}</td><td>${manager()||a.owner===person()||doc().pillars[c.pillar].owner===person()?btn('Update','activity',c.id+':'+a.id,'link'):''}</td></tr>`))}`,'Save result / references'));
  if(!allowed){$('#program-result').querySelectorAll('input,textarea,select,button[type=submit]').forEach(e=>e.disabled=true);return;}saveForm('program-result',async(v,f)=>{if(['Passed','Failed'].includes(v.status)&&!v.resultNote.trim())throw Error('Enter the review rationale.');if(v.status==='Passed'&&c.requiresLink&&!collectLinks(f).length)throw Error('Add the required reference link before passing.');await persist('result',{id:c.id,status:v.status,actual:v.actual||'',resultNote:v.resultNote,links:collectLinks(f)});});
 }
 function pillarSettings(code){const p=doc().pillars[code];if(!canConfigure(code))throw Error('Pillar owner required.');modal(code+' ownership',form('program-pillar-settings',`${manager()?personSelect('owner','Pillar owner / sponsor',p.owner):'<p>Owner: '+esc(name(p.owner))+'</p>'}${input('weight','Pillar weight in overall readiness',p.weight,'number','min="0.01" step="any" required')}<p class="help">Assign teammates in Scopes & People. Criterion and activity assignments are configured in the wizard.</p>`));saveForm('program-pillar-settings',async v=>persist('pillar',{code,value:{...p,owner:v.owner??p.owner,weight:Number(v.weight)}}));}
 function defaultsModal(id){const p=doc().pillars[pillar],b=p.buckets.find(x=>x.id===id);modal(b.name+' defaults',form('program-defaults',`${assignments({...b.defaults,milestoneIds:b.defaults.milestoneIds||[]})}${check('apply','Preview application to existing items in this bucket')}<p>New criteria inherit these fields. Explicit item overrides are preserved.</p>`));saveForm('program-defaults',async v=>{const defaults=getAssignments(v),next=structuredClone(p);next.buckets.find(x=>x.id===id).defaults=defaults;await persist('pillar',{code:pillar,value:next});if(v.apply){const items=doc().criteria.filter(c=>c.pillar===pillar&&c.bucket===id);setTimeout(()=>bulkModal(items,defaults),0);}});}
 function bulkModal(items=null,defaults=null){const targets=items||doc().criteria.filter(c=>selected.has(c.id)&&c.pillar===pillar);if(!targets.length)throw Error('Select criteria first.');modal('Preview shared assignments',form('program-bulk',`<p>${targets.length} criteria will be considered. Only populated fields are applied. Individual overrides are preserved unless explicitly replaced.</p>${assignments({...defaults,milestoneIds:defaults?.milestoneIds||[]})}${check('force','Replace explicit individual overrides as well')}${table(['Criterion','Current owner','Current reviewer'],targets.map(c=>`<tr><td>${esc(c.title)}</td><td>${esc(name(c.owner))}</td><td>${esc(name(c.reviewer))}</td></tr>`))}`,'Apply shared assignments'));saveForm('program-bulk',async v=>{const values=defaults||Object.fromEntries(Object.entries(getAssignments(v)).filter(([k,val])=>Array.isArray(val)?val.length:!!val));for(const original of targets){const c=doc().criteria.find(x=>x.id===original.id);await persist('criterion',applyDefaults(c,values,!!v.force));}selected.clear();});}
 function bucketsModal(code){const p=doc().pillars[code];modal('Edit parent buckets',form('program-buckets',`<p>Rename buckets or add your own. Remove a bucket only after its criteria are reassigned or removed.</p><div id="program-buckets-list">${p.buckets.map(b=>`<div class="program-bucket-row" data-bucket-id="${esc(b.id)}">${input('bucket-name','Bucket name',b.name,'text','required')}${btn('Remove','remove-bucket','','link')}</div>`).join('')}</div>${btn('Add bucket','add-bucket')}`));saveForm('program-buckets',async(v,f)=>{const buckets=[...f.querySelectorAll('.program-bucket-row')].map(r=>{const id=r.dataset.bucketId,old=p.buckets.find(b=>b.id===id);return {...old,id,name:r.querySelector('input').value,folderName:r.querySelector('input').value,defaults:old?.defaults||{}};});if(doc().criteria.some(c=>c.pillar===code&&!buckets.some(b=>b.id===c.bucket)))throw Error('A removed bucket still has criteria. Remove or move those criteria first.');await persist('pillar',{code,value:{...p,buckets,setupComplete:false}});bucket='';});}
 function samplingModal(){modal('Customer commissioning QA plan',form('program-sampling',`${doc().sampling.map(s=>`<fieldset data-stage="${s.stage}"><legend>${s.stage}</legend><div class="grid three">${input('percent_'+s.stage,'Inspection target (%)',s.percent,'number','min="0" max="100" step="any" required')}${input('population_'+s.stage,'Total population',s.population,'number','min="0" step="1" required')}${select('unit_'+s.stage,'Population unit',['Test events','Equipment','Scripts'].map(x=>opt(x,x,s.unit)).join(''))}${personSelect('owner_'+s.stage,'Default field auditor',s.owner)}${personSelect('reviewer_'+s.stage,'Default reviewer',s.reviewer)}${input('weight_'+s.stage,'Readiness weight',s.weight,'number','min="0.01" step="any" required')}</div>${input('scriptLink_'+s.stage,'Controlled script / script folder link',s.scriptLink,'url')}${input('sourceLink_'+s.stage,'Schedule / population source link',s.sourceLink,'url')}${area('inspectionCriteria_'+s.stage,'Default inspection checks and passing conditions',s.inspectionCriteria||'')}${check('gating_'+s.stage,'Unmet coverage or failed inspections gate this stage',s.gating)}</fieldset>`).join('')}<p class="help">Choose 0% for stages outside your assurance scope. The imported schedule can supply event counts; confirm that it represents your chosen population.</p>`));saveForm('program-sampling',async v=>persist('settings',{sampling:doc().sampling.map(s=>({...s,percent:Number(v['percent_'+s.stage]),population:Number(v['population_'+s.stage]),unit:v['unit_'+s.stage],owner:v['owner_'+s.stage],reviewer:v['reviewer_'+s.stage],weight:Number(v['weight_'+s.stage]),scriptLink:v['scriptLink_'+s.stage],sourceLink:v['sourceLink_'+s.stage],inspectionCriteria:v['inspectionCriteria_'+s.stage],gating:!!v['gating_'+s.stage],explicitPopulation:true}))}));}
 function generateAudits(){const stages=doc().sampling.filter(s=>Number(s.percent)>0);if(!stages.length)throw Error('Configure a sampling percentage first.');modal('Select inspection events',form('program-generate',`<p>Select the events your team will inspect. Equipment, dates and stage come from your imported schedule. Your choices determine the sample.</p>${select('stage','Stage',stages.map(s=>opt(s.stage,s.stage,stages[0].stage)).join(''),'id="program-audit-stage"')}<div id="program-audit-candidates"></div><h3>Or add one defined inspection</h3>${input('manualTitle','Inspection title')}${input('manualAsset','Equipment tag')}${input('manualDate','Planned inspection date','','date')}`,'Create assigned inspections'));
  function candidates(){const stage=$('#program-audit-stage').value,s=doc().sampling.find(x=>x.stage===stage),q=samplingStats(doc(),s);const events=st().data.schedule_activities.filter(a=>a.level===stage&&!doc().audits.some(x=>x.activityId===a.id));$('#program-audit-candidates').innerHTML=`<p>${q.needed} required · ${q.observed} observed · ${doc().audits.filter(a=>a.stage===stage).length} assigned. Default auditor: ${esc(name(s.owner))}.</p>${events.length?events.map(a=>check('event_'+a.id,a.external_id+' · '+a.name+' · '+(a.start_date||'date not set'),false)).join(''):'<p>No unassigned schedule events for this stage. Import the schedule or define an inspection below.</p>'}`;}candidates();$('#program-audit-stage').onchange=candidates;
  saveForm('program-generate',async v=>{const s=doc().sampling.find(s=>s.stage===v.stage),events=st().data.schedule_activities.filter(a=>v['event_'+a.id]);const audits=events.map(a=>({id:uid(),stage:s.stage,title:a.name,activityId:a.id,assetCode:a.asset_code,date:a.start_date||a.finish_date||'',scriptLink:s.scriptLink,inspectionCriteria:s.inspectionCriteria||'',links:[],owner:s.owner,reviewer:s.reviewer,status:'Not started',findings:'',resultNote:'',observedOn:''}));if(v.manualTitle.trim())audits.push({id:uid(),stage:s.stage,title:v.manualTitle,activityId:'',assetCode:v.manualAsset,date:v.manualDate,scriptLink:s.scriptLink,inspectionCriteria:s.inspectionCriteria||'',links:[],owner:s.owner,reviewer:s.reviewer,status:'Not started',findings:'',resultNote:'',observedOn:''});if(!audits.length)throw Error('Select an event or define an inspection.');await persist('audits',audits);});
 }
 function auditModal(id){const a=doc().audits.find(a=>a.id===id);if(!a)throw Error('Inspection not found.');const verdict=manager()||context.canReview||a.reviewer===person(),allowed=manager()||verdict||a.owner===person();modal(a.stage+' · '+a.title,form('program-audit',`<p>Equipment: ${esc(a.assetCode||'Not linked')} · Auditor: ${esc(name(a.owner))}</p>${manager()?`<div class="grid two">${personSelect('owner','Assigned auditor',a.owner)}${personSelect('reviewer','Assigned reviewer',a.reviewer)}${input('date','Inspection due date',a.date,'date')}</div>`:''}${manager()?area('inspectionCriteria','Defined inspection checks / passing conditions',a.inspectionCriteria||'','required'):'<div class="callout"><b>Inspection criteria</b><p>'+esc(a.inspectionCriteria||'Not defined')+'</p></div>'}${input('scriptLink','Applicable test script reference',a.scriptLink,'url')}${link(a.scriptLink,'Open test script')}<div class="grid two">${select('status','Inspection status',(verdict?['Not started','In progress','Submitted','Passed','Failed']:['Not started','In progress','Submitted']).map(x=>opt(x,x,a.status)).join(''))}${input('observedOn','Actual observation date',a.observedOn,'date')}</div>${area('resultNote','Inspection checks, passing criteria and observed result',a.resultNote)}${area('findings','Findings / required retest',a.findings)}<h3>External references / inspection results</h3>${linksEditor(a.links||[])}`));if(!allowed||doc().closedAt){$('#program-audit').querySelectorAll('input,textarea,select,button[type=submit]').forEach(x=>x.disabled=true);return;}saveForm('program-audit',async(v,f)=>persist('audit',{...a,...v,links:collectLinks(f)}));}
 function inputsConfig(){modal('Required building inputs',form('program-inputs-config',`${doc().inputs.map(i=>`<fieldset><legend>${esc(i.title)}</legend>${personSelect('owner_'+i.id,'Input coordinator',i.owner)}${input('provider_'+i.id,'Providing party',i.provider)}${input('due_'+i.id,'Due date',i.due,'date')}${check('required_'+i.id,'Receipt gates initial setup',i.required)}</fieldset>`).join('')}`));saveForm('program-inputs-config',async v=>persist('settings',{inputs:doc().inputs.map(i=>({...i,owner:v['owner_'+i.id],provider:v['provider_'+i.id],due:v['due_'+i.id],required:!!v['required_'+i.id]}))}));}
 function inputModal(id){const i=doc().inputs.find(i=>i.id===id);modal(i.title,form('program-input',`<p>Provider: ${esc(i.provider||'Not specified')} · Coordinator: ${esc(name(i.owner))}</p>${input('link','External document / repository link',i.link,'url')}${select('status','Receipt status',['Missing','Requested','Received'].map(x=>opt(x,x,i.status)).join(''))}${area('note','Receipt / coordination note',i.note||'')}${i.recordCount?'<p>'+i.recordCount+' records imported</p>':''}`));saveForm('program-input',async v=>persist('input',{id,...v}));}
 function milestoneModal(id=''){const m=doc().milestones.find(x=>x.id===id)||{id:'CUSTOM-'+uid().slice(0,8),name:'',date:'',originalDate:'',owner:doc().setup.owner,approver:doc().setup.owner,dependencyIds:[],acceptedAt:''};modal(id?'Configure milestone':'Add custom milestone',form('program-milestone-edit',`${input('name','Milestone name',m.name,'text','required')}${input('date','Target date',m.date,'date')}${personSelect('owner','Accountable milestone owner',m.owner)}${personSelect('approver','Acceptance authority',m.approver)}${area('note','Scope / purpose / target-date change reason',m.note||'')}<fieldset><legend>Required predecessor acceptances (optional)</legend>${doc().milestones.filter(x=>x.id!==m.id).map(x=>check('dep_'+x.id,x.name,m.dependencyIds.includes(x.id))).join('')}</fieldset><p class="help">Criteria and assurance targets establish the acceptance basis. Dates do not confer readiness.</p>`));saveForm('program-milestone-edit',async v=>{if(m.date&&m.date!==v.date&&!v.note.trim())throw Error('Record why the target date changed.');const next={...m,name:v.name,date:v.date,note:v.note,owner:v.owner,approver:v.approver,originalDate:m.originalDate||v.date,dependencyIds:doc().milestones.filter(x=>v['dep_'+x.id]).map(x=>x.id)},milestones=id?doc().milestones.map(x=>x.id===m.id?next:x):doc().milestones.concat(next);if(milestoneCycle(milestones))throw Error('Milestone dependencies cannot contain a cycle.');await persist('milestones',milestones);});}
 function milestoneView(id){const m=doc().milestones.find(m=>m.id===id),r=readiness(doc(),id);modal(m.name,`<div class="row">${badge(m.acceptedAt?(r.eligible?'Accepted':'Degraded'):r.eligible?'Eligible for acceptance':r.hasBasis?'Blocked':'Not configured')}<span>${esc(m.date||'No target date')} · ${esc(ago(m.date))}</span></div><p>Accountable owner: ${esc(name(m.owner))}<br>Accepting authority: ${esc(name(m.approver))}</p>${r.blockers.length?'<ul>'+r.blockers.map(b=>'<li>'+esc(b.title)+' · '+esc(name(b.owner))+'</li>').join('')+'</ul>':''}${!r.hasBasis?'<p>Define customer criteria or an assurance scope for this milestone.</p>':''}${criterionTable(activeCriteria(doc()).filter(c=>c.milestoneIds.includes(id)))}${id==='LIVE'?reviewStep().replace(/<button[\s\S]*?Review go-live decision[\s\S]*?<\/button>/,''):''}${r.eligible&&!doc().closedAt&&(manager()||m.approver===person())?form('program-accept',area('note','Customer acceptance rationale','','required'),'Record acceptance'):''}${manager()&&!doc().closedAt?btn('Configure milestone','edit-milestone',id):''}`);if($('#program-accept'))saveForm('program-accept',async v=>persist('accept',{id,note:v.note}));}
 function folderModal(id=''){const original=doc().folders.find(f=>f.id===id)||{id:uid(),name:'',pillar,bucket,parentId:''};modal(id?'Edit directory folder':'Add directory subfolder',form('program-folder',`${input('name','Folder name',original.name,'text','required')}${select('pillar','Pillar',opt('','Building root',original.pillar)+doc().selected.map(code=>opt(code,code,original.pillar)).join(''))}${select('bucket','Parent bucket (optional)',opt('','Pillar root',original.bucket)+doc().selected.flatMap(code=>doc().pillars[code].buckets.map(b=>opt(b.id,code+' / '+b.name,original.bucket))).join(''))}${select('parentId','Or parent custom folder',opt('','Use pillar / bucket',original.parentId)+doc().folders.filter(f=>f.id!==original.id).map(f=>opt(f.id,f.name,original.parentId)).join(''))}<p class="help">This changes the reference directory and exported template. It does not move external files.</p>${id?check('remove','Remove this empty custom folder'):''}`));saveForm('program-folder',async v=>{if(v.remove&&(doc().folders.some(f=>f.parentId===id)||directoryEntries(doc()).some(e=>e.folderId===id)))throw Error('Move its subfolders and references before removing this folder.');if(v.bucket&&!doc().pillars[v.pillar]?.buckets.some(b=>b.id===v.bucket))throw Error('Choose a bucket in the selected pillar.');const next=doc().folders.filter(f=>f.id!==original.id).concat(v.remove?[]:[{id:original.id,name:v.name,pillar:v.pillar,bucket:v.bucket,parentId:v.parentId}]);folderPaths({...doc(),folders:next},st().site.building);await persist('settings',{folders:next});});}
 function activityModal(value){const [cid,id]=value.split(':'),c=doc().criteria.find(c=>c.id===cid),a=c.activities.find(a=>a.id===id);modal(a.title,form('program-activity',`${select('status','Activity status',['Not started','In progress','Complete'].map(x=>opt(x,x,a.status)).join(''))}${area('note','Contribution / coordination result',a.note||'')}<h3>External references</h3>${linksEditor(a.links||[])}`));saveForm('program-activity',async(v,f)=>persist('activity',{criterionId:cid,id,...v,links:collectLinks(f)}));}
 function initialize(){const s=st(),owners=Object.fromEntries((s.data.site_verticals||[]).map(v=>[v.vertical_code,v.owner_person_id||'']));return persist('initialize',makeProgram({owner:person()||roster()[0]?.id||'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,scopeOwners:owners}));}
 function startTrial(){let saved;try{saved=JSON.parse(sessionStorage.getItem('threshold-trial'));}catch{}if(saved){trial=saved.trial;context=saved.context;}else{const id=uid(),personId=uid();trial={site:{id,building:'Trial Building',name:'Trial Building'},people:[{id:personId,display_name:'Trial program owner',active:true},{id:uid(),display_name:'Trial pillar owner',active:true},{id:uid(),display_name:'Trial field auditor',active:true},{id:uid(),display_name:'Trial reviewer',active:true}],data:{assets:[],schedule_activities:[],site_verticals:[]},manage:true};context={document:makeProgram({owner:personId,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}),revision:1,manager:true,personId,editablePillars:PILLARS.map(p=>p.code),canReview:true};}setStep(Number(sessionStorage.getItem('threshold-step:'+trial.site.id)||0));return trial;}
 async function handle(action,id,element){await flush();if(doc()?.closedAt&&!['home','directory','milestone','export-folders','export-index','local-folders','reopen','leave-trial','history','result','audit'].includes(action))throw Error('This building is archived; reopen it before editing.');
  if(action==='home')return navigate('setup');if(action==='new-build'){if(trial)throw Error('Leave the trial to create a customer building.');return createBuild();}if(action==='initialize'){await initialize();return navigate('program-wizard');}if(action==='wizard')return navigate('program-wizard');if(action==='step'){setStep(Number(id));return navigate('program-wizard');}if(action==='pillar'){pillar=id;bucket='';setStep(2);return navigate('program-wizard');}if(action==='qa')return navigate('program-qa');if(action==='milestones')return navigate('program-milestones');if(action==='directory')return navigate('program-directory');
  if(action==='pillar-settings')return pillarSettings(id);if(action==='new-criterion'){bucket=id;return criterionModal();}if(action==='criterion')return criterionModal(id);if(action==='duplicate')return criterionModal(id,true);if(action==='result')return resultModal(id);if(action==='defaults')return defaultsModal(id);if(action==='bulk')return bulkModal();if(action==='buckets')return bucketsModal(id);
  if(action==='complete-pillar'){const gaps=setupGaps(doc(),id);if(gaps.length)throw Error(gaps.slice(0,5).join('; '));await persist('pillar',{code:id,value:{...doc().pillars[id],setupComplete:true}});return paintNow();}
  if(action==='remove-criterion'){const c=doc().criteria.find(c=>c.id===id);modal('Remove criterion',form('program-remove',`<p>Remove ${esc(c.title)} from current readiness? Its earlier versions remain in the building history.</p>`,'Remove criterion'));return saveForm('program-remove',async()=>persist('remove_criterion',{id,pillar:c.pillar}));}
  if(action==='add-link'){$('#program-links').insertAdjacentHTML('beforeend',linkRow());return;}if(action==='remove-link'){element.closest('.program-link-row').remove();return;}if(action==='add-activity'){$('#program-activities').insertAdjacentHTML('beforeend',activityRow());return;}if(action==='remove-activity'){element.closest('.program-activity-row').remove();return;}if(action==='add-bucket'){$('#program-buckets-list').insertAdjacentHTML('beforeend',`<div class="program-bucket-row" data-bucket-id="${uid()}">${input('bucket-name','Bucket name','','text','required')}${btn('Remove','remove-bucket','','link')}</div>`);return;}if(action==='remove-bucket'){element.closest('.program-bucket-row').remove();return;}
  if(['same-previous','use-defaults'].includes(action)){const f=$('#program-criterion'),original=JSON.parse(f.dataset.original),b=doc().pillars[pillar].buckets.find(b=>b.id===bucket);const previous=doc().criteria.filter(c=>c.pillar===pillar&&c.bucket===bucket&&c.id!==original.id).at(-1),source=action==='use-defaults'?b.defaults:previous;if(!source)throw Error('No previous criterion in this bucket.');for(const key of ASSIGNMENT_FIELDS){if(key==='milestoneIds'){for(const m of doc().milestones)f.querySelector('[name="mile_'+m.id+'"]').checked=source.milestoneIds?.includes(m.id)||false;}else f.querySelector('[name='+key+']').value=source[key]||'';}return;}
  if(action==='sampling')return samplingModal();if(action==='generate-audits')return generateAudits();if(action==='audit')return auditModal(id);if(action==='inputs-config')return inputsConfig();if(action==='input')return inputModal(id);if(action==='import')return trial?trialImport(id):importRecords(id);if(action==='new-milestone')return milestoneModal();if(action==='edit-milestone')return milestoneModal(id);if(action==='milestone')return milestoneView(id);if(action==='new-folder')return folderModal();if(action==='edit-folder')return folderModal(id);if(action==='activity')return activityModal(id);
  if(action==='export-folders'){const entries=directoryEntries(doc()),index=$('#program-export-index')?.checked?linkIndex(entries,st().site.building):'';downloadBlob(folderZip(folderPaths(doc(),st().site.building),index),'Threshold-Folder-Structure.zip');return;}
  if(action==='export-index'){downloadBlob(new Blob([linkIndex(directoryEntries(doc()),st().site.building)],{type:'text/html'}),'Threshold-Link-Index.html');return;}
  if(action==='local-folders'){const index=$('#program-export-index')?.checked?linkIndex(directoryEntries(doc()),st().site.building):'';const n=await createLocalFolders(doc(),st().site.building,index);notice(n+' folders created in your selected location.');return;}
  if(action==='reopen'){modal('Reopen building',form('program-reopen',area('note','Reason for reopening','','required'),'Reopen'));return saveForm('program-reopen',async v=>persist('reopen',{note:v.note}));}
  if(action==='leave-trial'){trial=null;location.hash='';location.reload();return;}
 }
 function trialImport(kind){modal('Import '+(kind==='assets'?'master equipment list':'commissioning schedule'),`<p>Trial import: records stay in this browser session.</p><label>CSV / XLSX<input type="file" id="program-trial-file" accept=".csv,.xlsx"></label><div id="program-trial-mapping"></div>`);$('#program-trial-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const parsed=await parseFile(file);$('#program-trial-mapping').innerHTML=form('program-trial-import',fields[kind].map(k=>select('map_'+k,labels[k],opt('','Not mapped','')+parsed.headers.map((h,i)=>opt(i,h,h.toLowerCase().replaceAll(' ','_')===k?i:'')).join(''))).join('')+input('link','Original source reference','','url','required'));saveForm('program-trial-import',async v=>{const records=mapRows(kind,parsed,Object.fromEntries(fields[kind].map(k=>[k,v['map_'+k]])),doc().milestones.map(m=>m.id)),key=kind==='assets'?'code':'external_id',table=kind==='assets'?'assets':'schedule_activities';trial.data[table]=trial.data[table].filter(a=>!records.some(r=>r[key]===a[key])).concat(records.map(r=>({...r,id:uid()})));const inputs=doc().inputs.map(i=>i.kind===kind?{...i,link:safeURL(v.link),recordCount:trial.data[table].length,status:'Received'}:i);await persist('settings',{inputs});await syncImported();});}catch(error){notice(error.message,true);}};}
 async function syncImported(){if(!doc()||!manager())return;const data=st().data,inputs=doc().inputs.map(i=>i.kind==='assets'?{...i,recordCount:data.assets.length,status:data.assets.length?'Received':i.status}:i.kind==='schedule'?{...i,recordCount:data.schedule_activities.length,status:data.schedule_activities.length?'Received':i.status}:i),sampling=doc().sampling.map(s=>s.explicitPopulation?s:{...s,population:data.schedule_activities.filter(a=>a.level===s.stage).length});if(JSON.stringify(inputs)!==JSON.stringify(doc().inputs)||JSON.stringify(sampling)!==JSON.stringify(doc().sampling))await persist('settings',{inputs,sampling});}
 return {load,dashboard,wizard,qaView,directoryView,milestonesView,historyView,mount,handle,flush,startTrial,trial:()=>trial,context:()=>context,syncImported};
}
